### ISSUE TITLE
awscc_wafv2_regex_pattern_set- API error ValidationException

### ISSUE THREAD

**Issue by jackywong-amazon** [hashicorp/terraform-provider-awscc#1000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)
Terraform v1.4.6 & v1.5.0 - both experience the same issue
on darwin_arm64

+ provider registry.terraform.io/hashicorp/awscc v0.53.0

* awscc_wafv2_regex_pattern_set

### Terraform Configuration Files

`resource awscc_wafv2_regex_pattern_set "this" {
  regular_expression_list = [ "IamABadRequest", "I@mAB@dRequest"  ]
  scope = "REGIONAL"

}`

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # awscc_wafv2_regex_pattern_set.this will be created
  + resource "awscc_wafv2_regex_pattern_set" "this" {
      + arn                     = (known after apply)
      + description             = (known after apply)
      + id                      = (known after apply)
      + name                    = (known after apply)
      + regular_expression_list = [
          + "IamABadRequest",
          + "I@mAB@dRequest",
        ]
      + scope                   = "REGIONAL"
      + tags                    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

awscc_wafv2_regex_pattern_set.this: Creating...
awscc_wafv2_regex_pattern_set.this: Creation complete after 8s [id=6762581c-276d-4dfa-a725-6fbbfafa6dfb]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behavior

The resource has successfully provision. However, if Terraform Plan or Terraform Destroy command is used, Terraform failed to fetch the existing resource as it failed at Identifier is not valid for identifier /properties/Name, /properties/Id, /properties/Scope

### Steps to Reproduce

1. Terraform Plan
2. Terraform Apply
3. Resource provision
4. Terraform Plan 

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # awscc_wafv2_regex_pattern_set.this will be created
  + resource "awscc_wafv2_regex_pattern_set" "this" {
      + arn                     = (known after apply)
      + description             = (known after apply)
      + id                      = (known after apply)
      + name                    = (known after apply)
      + regular_expression_list = [
          + "IamABadRequest",
          + "I@mAB@dRequest",
        ]
      + scope                   = "REGIONAL"
      + tags                    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

awscc_wafv2_regex_pattern_set.this: Creating...
awscc_wafv2_regex_pattern_set.this: Creation complete after 8s [id=6762581c-276d-4dfa-a725-6fbbfafa6dfb]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

jackylw@3c0630438485 awscc_wafv2_regex_pattern_set % terraform plan
awscc_wafv2_regex_pattern_set.this: Refreshing state... [id=6762581c-276d-4dfa-a725-6fbbfafa6dfb]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: AWS SDK Go Service Operation Unsuccessful
│ 
│   with awscc_wafv2_regex_pattern_set.this,
│   on awscc_wafv2_regex_pattern_set.tf line 1, in resource "awscc_wafv2_regex_pattern_set" "this":
│    1: resource awscc_wafv2_regex_pattern_set "this" {
│ 
│ Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID:
│ ad5b50fb-dff4-428d-835e-c43fd7dbd0f4, api error ValidationException: Identifier 6762581c-276d-4dfa-a725-6fbbfafa6dfb is not valid for identifier [/properties/Name, /properties/Id,
│ /properties/Scope]

1. `terraform apply`

### References

TFStatefile

{
  "version": 4,
  "terraform_version": "1.5.0",
  "serial": 1,
  "lineage": "532e6ba8-122f-7508-5862-17609cc2f561",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "awscc_wafv2_regex_pattern_set",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/hashicorp/awscc\"]",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "arn": "arn:aws:wafv2:us-east-1:***********:regional/regexpatternset/2fuLMqJfHwsFz4jtwCdrfsZWs-jbv5ciazVqXk/6762581c-276d-4dfa-a725-6fbbfafa6dfb",
            "description": "",
            "id": "6762581c-276d-4dfa-a725-6fbbfafa6dfb",
            "name": "2fuLMqJfHwsFz4jtwCdrfsZWs-jbv5ciazVqXk",
            "regular_expression_list": [
              "IamABadRequest",
              "I@mAB@dRequest"
            ],
            "scope": "REGIONAL",
            "tags": null
          },
          "sensitive_attributes": []
        }
      ]
    }
  ],
  "check_results": null
}

* #0000

**Comment by wellsiau-aws** [comment]
Thanks for reporting this, I suspect this is relates to #999

**Comment by wellsiau-aws** [comment]
Confirmed that this is a similar pattern:
```
aws cloudcontrol create-resource \
  --type-name AWS::WAFv2::RegexPatternSet \
  --desired-state "{\"RegularExpressionList\": [\"^foobar$\"],\"Scope\":\"REGIONAL\"}"

{
    "ProgressEvent": {
        "TypeName": "AWS::WAFv2::RegexPatternSet",
        "RequestToken": "6a216bb8-49e9-4113-b687-d50c4e66d151",
        "Operation": "CREATE",
        "OperationStatus": "IN_PROGRESS",
        "EventTime": "2023-06-19T08:25:54.215000-07:00"
    }
}

aws cloudcontrol get-resource-request-status --request-token 6a216bb8-49e9-4113-b687-d50c4e66d151

{
    "ProgressEvent": {
        "TypeName": "AWS::WAFv2::RegexPatternSet",
        "Identifier": "WSSbWMqRBksR29nLKehNfQAOS-AosONbB579FI|778df032-b91c-429e-b3e4-c15bf3b2b0ad|REGIONAL",
        "RequestToken": "6a216bb8-49e9-4113-b687-d50c4e66d151",
        "Operation": "CREATE",
        "OperationStatus": "SUCCESS",
        "EventTime": "2023-06-19T08:25:54.624000-07:00"
    }
}
```

"Identifier": "WSSbWMqRBksR29nLKehNfQAOS-AosONbB579FI|778df032-b91c-429e-b3e4-c15bf3b2b0ad|REGIONAL"`
