### ISSUE TITLE
Cannot create more than 1 channel configuration "Slack channel with ID in Slack team has already been configured for AWS account.

### ISSUE THREAD

**Issue by ragincajunbanjo** [hashicorp/terraform-provider-awscc#1011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.4.0
+ provider registry.terraform.io/hashicorp/awscc v0.54.0

### Affected Resource(s)

* awscc_chatbot_slack_channel_configuration

### Terraform Configuration Files
```hcl
resource "awscc_chatbot_slack_channel_configuration" "pipeline-alert-slackbot" {
  # Slack-specific configuration
  for_each           = var.codepipelines
  slack_channel_id   = var.slack_channel_id 
  slack_workspace_id = var.slack_workspace_id
  configuration_name = each.key
  iam_role_arn       = var.iam_role_arn
  sns_topic_arns     = var.sns_topic_arns
  }
```
```hcl
codepipelines = {
        accounting_accounts_receivable_list_writer = "arn:aws:codepipeline:us-west-2:XXXXXXXXXXXX:accounting-accounts-receivable-list-writer"
        accounting_accounts_receivable_query = "arn:aws:codepipeline:us-west-2:XXXXXXXXXXXX:foo-bar-receivable-query"
        accounting_all_account_list_v1_writer = "arn:aws:codepipeline:us-west-2:XXXXXXXXXXXX:foo-bar-account-list-v1-writer"
        accounting_all_service_list_v1_writer = "arn:aws:codepipeline:us-west-2:XXXXXXXXXXXX:foo-bar-service-list-v1-writer"
}
slack_channel_id      = "C35EG51S5S" #(Obfuscated)
slack_workspace_id = "LSO3IKE03" #(Obfuscated)
iam_role_arn             = "arn:aws:iam::XXXXXXXXXXXX:role/admin-access"
sns_topic_arns         = ["arn:aws:sns:us-west-2:XXXXXXXXXXXX:codepipeline-failure-notifications"]
```
        
Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

### Debug Output
```bash
Error: AWS SDK Go Service Operation Incomplete
│ 
│   with awscc_chatbot_slack_channel_configuration.pipeline-alert-slackbot["accounting_accounts_receivable_list_writer"],
│   on main.tf line 17, in resource "awscc_chatbot_slack_channel_configuration" "pipeline-alert-slackbot":
│   17: resource "awscc_chatbot_slack_channel_configuration" "pipeline-alert-slackbot" {
│ 
│ Waiting for Cloud Control API service CreateResource operation completion
│ returned: waiter state transitioned to FAILED. StatusMessage: Invalid
│ request provided: Slack channel with ID C35EG51S5S in Slack team LUIOSKEN19
│ has already been configured for AWS account XXXXXXXXXXXX. (Service:
│ AWSChatbot; Status Code: 400; Error Code: InvalidRequestException; Request
│ ID: cda06s8dd-121f-4938-a1fd-01b1cc9a6d7c; Proxy: null). ErrorCode:
│ InvalidRequest
```

It does create 1 of the configurations, but doesn't add any additional, regardless of how many times I run it. I CAN do it through the GUI, but i'm trying to get this working with Terraform/Terragrunt
### Expected Behavior

I would expect to see multiple channel configs within the organization.

### Actual Behavior

It only creates 1 and abandons the rest.

### Steps to Reproduce

1. `terraform apply`

### References
* #0000

**Comment by luongdangvp2000** [comment]
Any updates to fix this issue? I face the same problem

**Comment by CloneOfAlex** [comment]
Is there any updates on this Bug?

**Comment by wellsiau-aws** [comment]
Looking at the AWS [docs](https://docs.aws.amazon.com/supportapp/latest/APIReference/API_CreateSlackChannelConfiguration.html), I understand that one Slack Channel can have more than 100 AWS accounts,  but it didnt specify that it allows multiple configuration from the same AWS account.

At such, can you instead create multiple [notification rules](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/codestarnotifications_notification_rule) per Codepipeline instance?

**Comment by wellsiau-aws** [comment]
I don't believe this is a bug, the returned error message is as expected since you cannot duplicate the slack channel for each AWS account.

@ragincajunbanjo , please have a look at my previous comment for the workaround, I am going to close this issue now.
