### ISSUE TITLE
Stale resource schema cache in repository

### ISSUE THREAD

**Issue by kadrach** [hashicorp/terraform-provider-awscc#1018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

81 stale schemas committed to repository, affecting 14 resources that can successfully be updated (more below).

### Expected Behavior

Provider is up to date using latest schemas from CFN registry.

### Actual Behavior

Generation for the provider uses stale schemas. Many schemas committed to this repository (internal/service/cloudformation/schemas/) are outdated. 

### Steps to Reproduce

```bash
% rm -rf internal/service/cloudformation/schemas
% AWS_DEFAULT_REGION=us-east-1 make schemas
% git diff --shortstat
81 files changed, 34245 insertions(+), 1663 deletions(-)
```

The updated schemas introduce a new set of issues (two top-level Ids introduced likely require disabling existing resources?):

```
error generating Terraform awscc_appflow_connector_profile resource: emitting schema code: isSandboxEnvironment overwrites IsSandboxEnvironment for Terraform attribute 
error generating Terraform awscc_ec2_network_insights_analysis resource: emitting schema code: DestinationCidr overwrites destinationCidr for Terraform attribute destination_cidr
error generating Terraform awscc_eks_cluster resource: emitting schema code: top-level property Id is not a primary identifier
error generating Terraform awscc_quicksight_data_set resource: emitting schema code: RowLevelPermissionTagConfiguration/TagRuleConfigurations is of unsupported type: list of array
error generating Terraform awscc_rum_app_monitor resource: emitting schema code: top-level property Id is not a primary identifier
error generating Terraform awscc_stepfunctions_state_machine resource: emitting schema code: DefinitionSubstitutions is of unsupported type: key-value map of
```

Additionally AWS::Lex::Bot causes a stackoverflow. 

These resources/data sources update successfully:

```
	modified:   internal/aws/cassandra/keyspace_resource_gen.go
	modified:   internal/aws/cassandra/keyspace_singular_data_source_gen.go
	modified:   internal/aws/connect/phone_number_resource_gen.go
	modified:   internal/aws/connect/phone_number_singular_data_source_gen.go
	modified:   internal/aws/dynamodb/global_table_resource_gen.go
	modified:   internal/aws/ec2/verified_access_instance_resource_gen.go
	modified:   internal/aws/ec2/verified_access_instance_singular_data_source_gen.go
	modified:   internal/aws/iotsitewise/asset_model_resource_gen.go
	modified:   internal/aws/kafkaconnect/connector_resource_gen.go
	modified:   internal/aws/kafkaconnect/connector_singular_data_source_gen.go
	modified:   internal/aws/mediaconnect/flow_resource_gen.go
	modified:   internal/aws/mediaconnect/flow_singular_data_source_gen.go
	modified:   internal/aws/mediaconnect/flow_source_resource_gen.go
	modified:   internal/aws/mediaconnect/flow_source_singular_data_source_gen.go
	modified:   internal/aws/networkmanager/transit_gateway_registration_resource_gen.go
	modified:   internal/aws/quicksight/analysis_resource_gen.go
	modified:   internal/aws/quicksight/analysis_singular_data_source_gen.go
	modified:   internal/aws/quicksight/dashboard_resource_gen.go
	modified:   internal/aws/quicksight/dashboard_singular_data_source_gen.go
	modified:   internal/aws/quicksight/template_resource_gen.go
	modified:   internal/aws/quicksight/template_singular_data_source_gen.go
	modified:   internal/aws/sagemaker/model_package_resource_gen.go
	modified:   internal/aws/sagemaker/model_package_singular_data_source_gen.go
	modified:   internal/aws/ssm/document_resource_gen.go
```

### References

* Similar scenario as AWS::Logs::LogStream in #1015

**Comment by ewbankkit** [comment]
Additionally

* AWS_QuickSight_Analysis.json
* AWS_QuickSight_Dashboard.json
* AWS_QuickSight_Template.json

cause the go1.20 compiler to report errors:

```
internal compiler error: NewBulk too big: nbit=29982 count=729981 nword=937 size=683992197
```

**Comment by kadrach** [comment]
```
% wc -l internal/aws/quicksight/dashboard_resource_gen.go 
  382203 internal/aws/quicksight/dashboard_resource_gen.go
```

Fairly complex/large schema, and the emitter generates this as one giant map. https://github.com/golang/go/issues/33437
