### ISSUE TITLE
Not able to create resource awscc_logs_log_group with data_protection_policy argument

### ISSUE THREAD

**Issue by naveen-amzn** [hashicorp/terraform-provider-awscc#1020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.2.0
+ provider registry.terraform.io/hashicorp/awscc v0.53.0

### Affected Resource(s)

* awscc_logs_log_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "awscc_logs_log_group" "this" {
  data_protection_policy = {
    "Name" : "data-protection-policy",
    "Description" : "",
    "Version" : "2021-06-01",
    "Statement" : <<EOF
    [
      {
        "Sid" : "audit-policy",
        "DataIdentifier" : [
          "arn:aws:dataprotection::aws:data-identifier/Address",
          "arn:aws:dataprotection::aws:data-identifier/DriversLicense-LV",
          "arn:aws:dataprotection::aws:data-identifier/DriversLicense-MT",
          "arn:aws:dataprotection::aws:data-identifier/DriversLicense-NL"
        ],
        "Operation" : {
          "Audit" : {
            "FindingsDestination" : {
              "S3" : {
                "Bucket" : "sample-fefeeef"
              }
            }
          }
        }
      }
    ]
    EOF
  }

  log_group_name    = "Sample"
  retention_in_days = 90
}
```

### Debug Output

1. awscc_logs_log_group is able to create resource with basic configuration. 
2. When I try to use `data_protection_policy` argument, it required map of string and I tried below options
    - using EOF to provide statement.
    - using jsonencode to provide statements.
    - using aws resource `aws_cloudwatch_log_data_protection_policy_document` to provide a data_protection_policy
3. This resource requires string value for `Statement` of `data_protection_policy` hence it is not able to parse it and fails with below error: 
```bash
awscc_logs_log_group.this: Creating...
╷
│ Error: AWS SDK Go Service Operation Incomplete
│ 
│   with awscc_logs_log_group.this,
│   on cloudwatch_log_group_with_dp_policy.tf line 1, in resource "awscc_logs_log_group" "this":
│    1: resource "awscc_logs_log_group" "this" {
│ 
│ Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED. StatusMessage: Failed to parse the data protection policy (Service: CloudWatchLogs,
│ Status Code: 400, Request ID: ff8ac9fa-aa37-45be-916c-952138517613). ErrorCode: InvalidRequest
```

### Expected Behavior

 AWS resource AWS CloudWatch log group should have been created with data protection policy.

### Actual Behavior

 Terraform awscc provider is not able to parse data_protection_policy argument. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by wellsiau-aws** [comment]
First of all, I tried to test the same `data_protection_policy` and CCAPI returned this:

```
{
    "ProgressEvent": {
        "TypeName": "AWS::Logs::LogGroup",
        "Identifier": "my-log-group2",
        "RequestToken": "ed1e68ea-0379-4634-b36f-c2ca5f6359c3",
        "Operation": "CREATE",
        "OperationStatus": "FAILED",
        "EventTime": "2023-06-26T21:50:42.662000-07:00",
        "StatusMessage": "Policy can only have two statements. One for Audit Operation and one for Deidentify Operation (Service: CloudWatchLogs, Status Code: 400, Request ID: a963edc1-e4e9-4197-92fe-0a73f150e8a6)",
        "ErrorCode": "InvalidRequest"
    }
}
```

As per documentation: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/mask-sensitive-log-data-start.html#mask-sensitive-log-data-start-cli

You **must** include two block of data protection policy:
* First block for Audit action
* Second block for Deidentify action

That said, this is only half of the problem.

**Comment by wellsiau-aws** [comment]
The `data_protection_policy` schema is defined as map of strings

https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/aws/logs/log_group_resource_gen.go#L55-L57

which makes it tricky to declare the `Statement` policy which should be a list of map.

not sure if there's any encoding functions that could help in here beside redefining the schema

**Comment by naveen-amzn** [comment]
@wellsiau-aws, yes I tried to provide policy in part that also failed. Initially I have tried to create resource with below policy.
```hcl
{
    Name    = "Example"
    Version = "2021-06-01"

    Statement = [
      {
        Sid            = "Audit"
        DataIdentifier = ["arn:aws:dataprotection::aws:data-identifier/EmailAddress"]
        Operation = {
          Audit = {
            FindingsDestination = {
              S3 = {
                Bucket = "sample-bucket-name-random"
              }
            }
          }
        }
      },
      {
        Sid            = "Redact"
        DataIdentifier = ["arn:aws:dataprotection::aws:data-identifier/EmailAddress"]
        Operation = {
          Deidentify = {
            MaskConfig = {}
          }
        }
      }
    ]
  })
```


It is failing as it needs `Statement` as string.

**Comment by wellsiau-aws** [comment]
relates to #836
