### ISSUE TITLE
awscc_sso_assignment fails when using awscc_sso_permission_set

### ISSUE THREAD

**Issue by novekm** [hashicorp/terraform-provider-awscc#1065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.5.3
on linux_amd64
provider.registry.terraform.io/hashicorp/awscc v0.55.0
provider.registry.terraform.io/hashicorp/aws v5.8.0

### Affected Resource(s)

* awscc_sso_permissions_set
* awscc_sso_assignment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
// Note: Currently there is no data source for fetching the sso instance arn in the awscc provider
// so we must use both the aws and awscc providers.
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    awscc = {
      source = "hashicorp/awscc"
    }
  }
}

data "aws_ssoadmin_instances" "example" {} // fetch IAM Identity Center instance arn

// create new permission set
resource "awscc_sso_permission_set" "example" {
  instance_arn = tolist(data.aws_ssoadmin_instances.example.arns)[0] // reference existing sso instance by arn
  name         = "ExamplePermissionSet"
  description  = "An example Permission Set"
  // add multiple managed policies
  managed_policies = [
    "arn:aws:iam::aws:policy/AdministratorAccess",
    "arn:aws:iam::aws:policy/job-function/ViewOnlyAccess",
  ]
  // redirect to S3 in us-east-1 upon sign-in
  relay_state_type = "https://s3.console.aws.amazon.com/s3/home?region=us-east-1#"
  // set 2 hour session duration
  session_duration = "PT2H"
}

data "aws_identitystore_group" "example" {
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]

  alternate_identifier {
    unique_attribute {
      attribute_path  = "DisplayName"
      attribute_value = "ExampleGroup" // fetch info for IAM IDC group with DisplayName of 'ExampleGroup'
    }
  }
}

resource "awscc_sso_assignment" "example" {
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = awscc_sso_permission_set.example.id

  principal_id   = data.aws_identitystore_group.example.group_id // reference group id that was fetched by the data source
  principal_type = "GROUP"                                       // valid values are 'USER' or 'GROUP'                                   // valid values are 'USER' or 'GROUP'

  target_id   = "111111111111"
  target_type = "AWS_ACCOUNT"

}

```

### Expected Behavior

IAM Identity Center assignment should have been created with the associated Permissions Set.

### Actual Behavior

Apply fails throwing the following error (relevant ids obfuscated for security)

```sh
│ Error: AWS SDK Go Service Operation Unsuccessful
│ 
│   with awscc_sso_assignment.example,
│   on main.tf line 44, in resource "awscc_sso_assignment" "example":
│   44: resource "awscc_sso_assignment" "example" {
│ 
│ Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error StatusCode: 400,
│ RequestID: xx-xx-xx-xx-xx, api error ValidationException: Identifier
│ arn:aws:sso:::instance/ssoins-xxxxxx|111111111111|AWS_ACCOUNT|arn:aws:sso:::instance/ssoins-xxxxxxx|arn:aws:sso:::permissionSet/ssoins-xxxxxxx/ps-xxxxxxx|GROUP|xx-xx-xx-xx-xx
│ is not valid for identifier [/properties/InstanceArn, /properties/TargetId, /properties/TargetType, /properties/PermissionSetArn,
│ /properties/PrincipalType, /properties/PrincipalId]
```
When this error arises all subsequent attempts to destroy resources via `terraform destroy` fail with the same error.

### Steps to Reproduce

1. `terraform apply` with the above configuration

### Important Factoids

No

### References

AWS provider `aws_ssoadmin_permission_set` - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_permission_set

* #0000

**Comment by wellsiau-aws** [comment]
In my test, the `awscc_sso_permission_set.example.id` is returning value in the following format:

`arn:aws:sso:::instance/ssoins-72235ca0ccd37342|arn:aws:sso:::permissionSet/ssoins-72235ca0ccd37342/ps-f51f2f233e613f4a`

Notice the `|` delimiter, the right value should only be the `arn:aws:sso:::permissionSet/ssoins-72235ca0ccd37342/ps-f51f2f233e613f4a`

**Comment by wellsiau-aws** [comment]
This happened when resource uses composite ID that contain combination of ARN and other identifier. Referring the same ID on another resource can throw error because other resource attribute did not expect a composite ID.

**Comment by wellsiau-aws** [comment]
@novekm , 

Can you try again by using [permission_set_arn](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/sso_permission_set#permission_set_arn) instead of id like below:

```
resource "awscc_sso_assignment" "example" {
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = awscc_sso_permission_set.example.permission_set_arn 

  principal_id   = data.aws_identitystore_group.example.group_id // reference group id that was fetched by the data source
  principal_type = "GROUP"                                       // valid values are 'USER' or 'GROUP'                                   // valid values are 'USER' or 'GROUP'

  target_id   = "111111111111"
  target_type = "AWS_ACCOUNT"

}

```
