### ISSUE TITLE
awscc_lex_resource_policy - The resource │ policy isn't valid. Check the policy format and try your request again

### ISSUE THREAD

**Issue by bpercy11** [hashicorp/terraform-provider-awscc#1103]
There needs to be better examples for the awscc_lex_resource_policy resource. I can't find any documentation and I can't find any actual examples of how to format this resource. The error keeps coming back that the formatting is incorrect. Please provide an actual working example with keys and values to help.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.0.8
on linux_amd64

### Affected Resource(s)

awscc_lex_resource_policy

### Terraform Configuration Files

resource "awscc_lex_resource_policy" "otp_lex_bot_alias_policy" {
    resource_arn = resource.awscc_lex_bot_alias.otp_lex_bot_alias.arn
    policy = {
      Version   = "2012-10-17"
      Statement =  "test-statement"
      Effect = "Allow"
      Principal = "connect.amazonaws.com"
      Action = "lex:RecognizeText"
      Resource = "*"
    }

    depends_on = [resource.awscc_lex_bot_alias.otp_lex_bot_alias]
}

### Debug Output

│ Error: AWS SDK Go Service Operation Incomplete
│
│   with awscc_lex_resource_policy.otp_lex_bot_alias_policy,
│   on lex_bot.tf line 161, in resource "awscc_lex_resource_policy" "otp_lex_bot_alias_policy":
│  161: resource "awscc_lex_resource_policy" "otp_lex_bot_alias_policy" {
│
│ Waiting for Cloud Control API service CreateResource operation completion
│ returned: waiter state transitioned to FAILED. StatusMessage: The resource
│ policy isn't valid. Check the policy format and try your request again.
│ (Service: LexModelsV2, Status Code: 400, Request ID:
│ 81f7ed61-5137-41f5-9c6e-ae8b5b595dfd). ErrorCode: InvalidRequest

**Comment by kadrach** [comment]
This relates to #514, I believe there is unfortunately no workaround at the moment.
