### ISSUE TITLE
awscc_gamelift_fleet error during creation

### ISSUE THREAD

**Issue by novekm** [hashicorp/terraform-provider-awscc#1121]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_gamelift_fleet

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
// Create GameLift Fleet from existing build
resource "awscc_gamelift_fleet" "example" {
  name              = "example-fleet-name"
  build_id          = "build-xxx"
  ec2_instance_type = "t2.micro"  // ensure instance type is supported for your desired region
  fleet_type        = "ON_DEMAND" // valid values are "ON_DEMAND" or "SPOT"

  runtime_configuration = {
    server_process = {
      concurrent_executions = 1
      launch_path           = "TestApplicationServer"
    }
  }
}
```

### Debug Output

Condensed output
```
│ Error: AWS SDK Go Service Operation Incomplete
│ 
│   with awscc_gamelift_fleet.example,
│   on main.tf line 2, in resource "awscc_gamelift_fleet" "example":
│    2: resource "awscc_gamelift_fleet" "example" {
│ 
│ Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED. StatusMessage: Invalid request provided: AWS::GameLift::Fleet.
│ ErrorCode: InvalidRequest
```
Full output: https://gist.github.com/novekm/7d2d42eca021743dbcb757911d43497e

### Expected Behavior
 
Resource should have been created successfully

### Actual Behavior

Resource was not created successfully. Error was thrown.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by wellsiau-aws** [comment]
From the debug I found :

diagnostic_detail="Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED. StatusMessage: Invalid or missing BuildId build-xxx (Service: GameLift, Status Code: 400,

You must specify valid `build_id` , let me know if the issue persisted, feel free to re-open this

**Comment by wellsiau-aws** [comment]
closing this issue since I am unable to replicate the issue
