### ISSUE TITLE
awscc_ec2_ipam_pool_cidr - no changes to args but pool and cidr force new

### ISSUE THREAD

**Issue by GlennChia** [hashicorp/terraform-provider-awscc#1140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* `awscc_ec2_ipam_pool_cidr`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Running `terraform apply` using the config below works and the resources are created as expected. However, running a `terraform plan` after the resources are created with no change to the configuration leads to an unexpected output that the resources must be replaced.

```hcl
data "aws_region" "current" {}

resource "awscc_ec2_ipam" "example" {
  operating_regions = [
    {
      region_name = data.aws_region.current.name
    }
  ]
}

resource "awscc_ec2_ipam_pool" "example" {
  address_family = "ipv4"
  ipam_scope_id  = awscc_ec2_ipam.example.private_default_scope_id
  locale         = data.aws_region.current.name
}

resource "awscc_ec2_ipam_pool_cidr" "example" {
  ipam_pool_id = awscc_ec2_ipam_pool.example.id
  cidr         = "10.0.0.0/16"
}
```

### Expected Behavior

Since the configuration has not changed, the plan should reflect `No changes. Your infrastructure matches the configuration.`

### Actual Behavior

Terraform shows that the pool and cidr must be destroyed and recreated although there are no changes to the hcl

```
data.aws_region.current: Reading...
data.aws_region.current: Read complete after 0s [id=ap-southeast-1]
awscc_ec2_ipam.example: Refreshing state... [id=ipam-example]
awscc_ec2_ipam_pool.example: Refreshing state... [id=ipam-pool-example]
awscc_ec2_ipam_pool_cidr.example: Refreshing state... [id=ipam-pool-example|ipam-pool-cidr-example]

Terraform used the selected providers to generate the following execution plan. Resource
actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # awscc_ec2_ipam_pool.example must be replaced
-/+ resource "awscc_ec2_ipam_pool" "example" {
      + allocation_default_netmask_length = (known after apply)
      + allocation_max_netmask_length     = (known after apply)
      + allocation_min_netmask_length     = (known after apply)
      + allocation_resource_tags          = (known after apply)
      ~ arn                               = "arn:aws:ec2::111122223333:ipam-pool/ipam-pool-example" -> (known after apply)
      ~ auto_import                       = false -> (known after apply)
      + aws_service                       = (known after apply) # forces replacement
      + description                       = (known after apply)
      ~ id                                = "ipam-pool-example" -> (known after apply)
      ~ ipam_arn                          = "arn:aws:ec2::111122223333:ipam/ipam-example" -> (known after apply)
      ~ ipam_pool_id                      = "ipam-pool-example" -> (known after apply)
      ~ ipam_scope_arn                    = "arn:aws:ec2::111122223333:ipam-scope/ipam-scope-example" -> (known after apply)
      ~ ipam_scope_type                   = "private" -> (known after apply)
      ~ pool_depth                        = 1 -> (known after apply)
      ~ provisioned_cidrs                 = [
          - {
              - cidr = "10.0.0.0/16" -> null
            },
        ] -> (known after apply)
      + public_ip_source                  = (known after apply) # forces replacement
      + publicly_advertisable             = (known after apply) # forces replacement
      + source_ipam_pool_id               = (known after apply) # forces replacement
      ~ state                             = "create-complete" -> (known after apply)
      ~ state_message                     = "None" -> (known after apply)
      + tags                              = (known after apply)
        # (3 unchanged attributes hidden)
    }

  # awscc_ec2_ipam_pool_cidr.example must be replaced
-/+ resource "awscc_ec2_ipam_pool_cidr" "example" {
      ~ id                = "ipam-pool-example|ipam-pool-cidr-example" -> (known after apply)
      ~ ipam_pool_cidr_id = "ipam-pool-cidr-example" -> (known after apply)
      ~ ipam_pool_id      = "ipam-pool-example" # forces replacement -> (known after apply) # forces replacement
      ~ netmask_length    = 16 -> (known after apply)
      ~ state             = "provisioned" -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 2 to add, 0 to change, 2 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

```hcl
data "aws_region" "current" {}

resource "awscc_ec2_ipam" "example" {
  operating_regions = [
    {
      region_name = data.aws_region.current.name
    }
  ]
}

resource "awscc_ec2_ipam_pool" "example" {
  address_family = "ipv4"
  ipam_scope_id  = awscc_ec2_ipam.example.private_default_scope_id
  locale         = data.aws_region.current.name
}

resource "awscc_ec2_ipam_pool_cidr" "example" {
  ipam_pool_id = awscc_ec2_ipam_pool.example.id
  cidr         = "10.0.0.0/16"
}
```

2. Run `terraform plan` and this shows that the some of the arguments of the cidr and pool `forces replacement` which is unexpected

### References

* PR with examples #1136

**Comment by kadrach** [comment]
A quick note: The example wants to replace both `awscc_ec2_ipam_pool` and `awscc_ec2_ipam_pool_cidr` resources. If the latter is removed, no changes are detected 😕

**Comment by wellsiau-aws** [comment]
Terraform debug logs

```
2023-09-11T16:11:15.406-0700 [WARN]  Provider "registry.terraform.io/hashicorp/awscc" produced an unexpected new value for awscc_ec2_ipam_pool.example during refresh.
      - .provisioned_cidrs: was null, but now cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"cidr":cty.StringVal("10.0.0.0/16")})})
```

**Comment by wellsiau-aws** [comment]
From IPAM workflow perspective, this make sense because:
1. `awscc_ec2_ipam_pool` is created with `provisioned_cidrs` = null because there aren't any utilization yet
2. `awscc_ec2_ipam_pool_cidr` carve new CIDR which then sync with the actual pool, however at this moment, `awscc_ec2_ipam_pool` state file is already out of sync

**Comment by wellsiau-aws** [comment]
So far the workaround is by adding `ignore_changes` lifecycle

```
resource "awscc_ec2_ipam_pool" "example" {
  address_family = "ipv4"
  ipam_scope_id  = awscc_ec2_ipam.example.private_default_scope_id
  locale         = data.aws_region.current.name
  lifecycle {
    ignore_changes = [
      provisioned_cidrs,
    ]
  }
}
```

I noticed during design of this resource on the AWS standard provider, we skipped the `provisioned_cidrs` attribute from the schema.

**Comment by wellsiau-aws** [comment]
@GlennChia , I think this is as expected due to how IPAM resource is modeled vs the API interaction. I suggest to add the lifecycle `ignore_changes` as workaround and perhaps make that call out in the example.

**Comment by wellsiau-aws** [comment]
closing this as documented known issue with a workaround.
