### ISSUE TITLE
awscc_config_config_rule - resource creation failing

### ISSUE THREAD

**Issue by alex-torres1980** [hashicorp/terraform-provider-awscc#1172]
**Terraform CLI and Terraform AWS Cloud Control Provider Version**
Admin:~/environment/us-east-1 $ terraform -v
Terraform v1.4.6
on linux_amd64

provider registry.terraform.io/hashicorp/aws v5.13.0
provider registry.terraform.io/hashicorp/awscc v0.58.0
Your version of Terraform is out of date! The latest version
is 1.5.5. You can update by downloading from https://www.terraform.io/downloads.html
Admin:~/environment/us-east-1 $

**Affected Resource(s)**
awscc_config_config_rule

**Terraform Configuration Files**
#resource for aws_config_config_rule using managed rule.
resource "awscc_config_config_rule" "r" {
  config_rule_name = "example1"
  description = "this is my first example"
  evaluation_modes = [{
    mode= "Detective"
  }]

  source = {
    owner = "AWS"
    #source_identifier = list of managed rules
    source_identifier = "S3_BUCKET_VERSIONING_ENABLED"
    custom_policy_details ={
      #policy_runtime = "guard-2.x.x" -- not needed because it is not custom
      enable_debug_log_delivery = false
      policy_text = <<EOF
      {
          "Version": "2012-10-17",
          "id": "abc"
          "Statement": [
              {
                  "Sid": "policyforconfigrule",
                  "Effect": "Allow",
                  "Principal": {
                      "AWS": [
                          "config.amazonaws.com"
                      ]
                  },
                  "Action": [
                      "config:Put*"
                  ],
                  "Resource": "*"
              }
          ]
      }
      EOF                    
  }
}
}

**Debug Output**
N/A

**Expected Behavior**
Enable Config rule

**Actual Behavior**
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # awscc_config_config_rule.r will be created
  + resource "awscc_config_config_rule" "r" {
      + arn                         = (known after apply)
      + compliance                  = (known after apply)
      + config_rule_id              = (known after apply)
      + config_rule_name            = "example1"
      + description                 = "this is my first example"
      + evaluation_modes            = [
          + {
              + mode = "Detective"
            },
        ]
      + id                          = (known after apply)
      + input_parameters            = (known after apply)
      + maximum_execution_frequency = (known after apply)
      + scope                       = (known after apply)
      + source                      = {
          + custom_policy_details = {
              + enable_debug_log_delivery = false
              + policy_runtime            = (known after apply)
              + policy_text               = <<-EOT
                    {
                              "Version": "2012-10-17",
                              "id": "abc"
                              "Statement": [
                                  {
                                      "Sid": "policyforconfigrule",
                                      "Effect": "Allow",
                                      "Principal": {
                                          "AWS": [
                                              "config.amazonaws.com"
                                          ]
                                      },
                                      "Action": [
                                          "config:Put*"
                                      ],
                                      "Resource": "*"
                                  }
                              ]
                          }
                EOT
            }
          + owner                 = "AWS"
          + source_details        = (known after apply)
          + source_identifier     = "S3_BUCKET_VERSIONING_ENABLED"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Error: Terraform Resource Identifier Not Found
│ 
│ Terraform resource primary identifier not found in State. This is typically an error with the Terraform provider implementation. Original Error: 1 error occurred:
│       * An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
│ 
│ Path: id
│ Target Type: string
│ Suggested `types` Type: basetypes.StringValue
│ Suggested Pointer Type: *string

Steps to Reproduce
Create a tf file and run Terraform init and then terraform apply.

Important Factoids
I am running from cloud9 environment. FYI, I was able to create topic and associate the policy using the original aws resource (awscc_config_config_rule)

**Comment by alex-torres1980** [comment]
Issue with my environment and code. After fixing I was able to run the config rule.

**Comment by wellsiau-aws** [comment]
@alex-torres1980 , I believe this is resolved now, please feel free to reopen the issue.

**Comment by alex-torres1980** [comment]
Yes, this one is working and I did the PR. Thank you for your support and help. this can be resolved.
