### ISSUE TITLE
Add awscc_verifiedpermissions resources

### ISSUE THREAD

**Issue by ryancausey** [hashicorp/terraform-provider-awscc#1235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

Please implement the awscc_verifiedpermissions resources. Currently they are only available as data sources. It looks like all of the API operations for them are currently supported by the AWS Cloud Control API.

### New or Affected Resource(s)

* awscc_verifiedpermissions_identity_source
* awscc_verifiedpermissions_policy
* awscc_verifiedpermissions_policy_store
* awscc_verifiedpermissions_policy_template

### Potential Terraform Configuration

```hcl
resource "awscc_verifiedpermissions_policy_store" "example" {
    schema {
        cedar_json = file("example.json")
    }
    validation_settings {
        mode = "STRICT"
    }
}

resource "awscc_verifiedpermissions_identity_store" "example" {
    policy_store_id = awscc_verifiedpermissions_policy_store.example.policy_store_id
    configuration {
        cognito_user_pool_configuration {
            client_ids = ["example1", "example2"]
            user_pool_arn = "arn::example"
        }
    }
    principal_entity_type = "Namespace::User"
}

resource "awscc_verifiedpermissions_policy" "example" {
    policy_store_id = awscc_verifiedpermissions_policy_store.example.policy_store_id
    type = "STATIC"
    definition {
        static {
            description = "Example description"
            statement = <<EOF
permit(
    principal,
    action,
    resource
);
EOF
        }
    }
}

resource "awscc_verifiedpermissions_policy_template" "example" {
    policy_store_id = awscc_verifiedpermissions_policy_store.example.policy_store_id
    description = "Example template description"
    statement = <<EOF
permit(
    principal = ?,
    action in Namespace::Action::"viewExample",
    resource = ?
);
EOF
}
```

### References

* https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-verifiedpermissions-identitysource.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-verifiedpermissions-policy.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-verifiedpermissions-policystore.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-verifiedpermissions-policytemplate.html

**Comment by kadrach** [comment]
It this not what you are after? https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/verifiedpermissions_policy_store

**Comment by ryancausey** [comment]
When I search for `verified` in the docs, this resources does not appear. Only the data sources are shown.
![image](https://github.com/hashicorp/terraform-provider-awscc/assets/2704075/b41fd8e3-0a79-4b33-b53a-70cd2e244a65)

**Comment by ryancausey** [comment]
These are now appearing in the docs correctly.
