### ISSUE TITLE
Top-level `id` attribute that is not a primary identifier

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-awscc#125]
There are a handful of resource types

* `awscc_groundstation_config`
* `awscc_opensearchservice_domain`
* `awscc_opsworkscm_server`
* `awscc_redshift_cluster`
* `awscc_s3outposts_endpoint`
* `awscc_synthetics_canary`

that declare their own top-level `Id` property in the CloudFormation schema, but it is not a primary identifier.
This conflicts with the assumptions we make for the synthesized `id` attribute.

For now, suppress resource generation for these resource types.

Relates:

* #156
* #121

**Comment by PeterBurner** [comment]
This issue has been open for some time now. Any news on this?
Can we do anything to help here? Is there maybe a PFR at AWS we can push?
If AWS won't or cannot fix this due to backwards compatibility maybe its time to think of alternative solutions?
