### ISSUE TITLE
awscc_s3_bucket_policy : CCAPI AccessDenied

### ISSUE THREAD

**Issue by wellsiau-aws** [hashicorp/terraform-provider-awscc#1261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_s3_bucket_policy

### Terraform Configuration Files

```hcl
resource "awscc_s3_bucket_policy" "example" {
  bucket = awscc_s3_bucket.example.id
  policy_document = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "AllowPublicRead",
        "Effect": "Allow",
        "Principal": "*",
        "Action": "s3:GetObject",
        "Resource": "${awscc_s3_bucket.example.arn}/*"
      }
    ]
  })
}

resource "awscc_s3_bucket" "example" {
}
```

### Actual Behavior

Error from AWSCC:

```
awscc_s3_bucket.example: Creating...
awscc_s3_bucket.example: Still creating... [10s elapsed]
awscc_s3_bucket.example: Still creating... [20s elapsed]
awscc_s3_bucket.example: Creation complete after 27s [id=41gjnbhid679zlrqfpumwjqdr-0htkkonny4fp]
awscc_s3_bucket_policy.example: Creating...
╷
│ Error: AWS SDK Go Service Operation Incomplete
│ 
│   with awscc_s3_bucket_policy.example,
│   on main.tf line 1, in resource "awscc_s3_bucket_policy" "example":
│    1: resource "awscc_s3_bucket_policy" "example" {
│ 
│ Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED. StatusMessage: Access Denied (Service: S3, Status Code: 403,
│ Request ID: REDACTED, Extended Request ID: REDACTED). ErrorCode: AccessDenied
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kadrach** [comment]
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

Need at minimum

```hcl
resource "awscc_s3_bucket" "example" {
  public_access_block_configuration = {
    block_public_policy = false
  }
}
```

**Comment by wellsiau-aws** [comment]
good catch, this is user error, closing now.
