### ISSUE TITLE
The terraform-provider-awscc_v0.68.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by crussell-square** [hashicorp/terraform-provider-awscc#1412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_elasticache_serverless_cache

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = "1.1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    awscc = {
      source  = "hashicorp/awscc"
      version = ">= 0.68.0"
    }
  }
}

provider "awscc" {
  region = "<region>"
  assume_role = {
    role_arn = "<arn>"
  }
}
```

```hcl
resource "awscc_elasticache_serverless_cache" "newTestElasticache" {
  engine = "redis"
  serverless_cache_name = "newTestElasticache"
  subnet_ids = <ids>
  security_group_ids = <ids>
}
```

### Debug Output

https://gist.github.com/crussell-square/9dfe372dc6902659c0a0d0890781e6a5

### Panic Output

https://gist.github.com/crussell-square/9dfe372dc6902659c0a0d0890781e6a5

### Expected Behavior

Terraform exit `apply` successfully.

### Actual Behavior

Terraform exited with the error described above.

### Steps to Reproduce

1. Add awscc as a provider per above and run `terraform init`
2. Add `awscc_elasticache_serverless_cache` resource and run `terraform plan`
3. `terraform apply`

### References

* #0000

**Comment by pratikpandey21** [comment]
The weird part is it did deploy successfully and started to crash just yesterday, all of a sudden.

**Comment by crussell-square** [comment]
Closing since duplicate and can workaround by using https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache
