### ISSUE TITLE
Feature Request: WorkSpaces Web Resources

### ISSUE THREAD

**Issue by dylanmtaylor** [hashicorp/terraform-provider-awscc#1427]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### New or Affected Resource(s)
[AWS::WorkSpacesWeb::BrowserSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-browsersettings.html)

[AWS::WorkSpacesWeb::IdentityProvider](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-identityprovider.html)

[AWS::WorkSpacesWeb::IpAccessSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-ipaccesssettings.html)

[AWS::WorkSpacesWeb::NetworkSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-networksettings.html)

[AWS::WorkSpacesWeb::Portal](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-portal.html)

[AWS::WorkSpacesWeb::TrustStore](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-truststore.html)

[AWS::WorkSpacesWeb::UserAccessLoggingSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-useraccessloggingsettings.html)

[AWS::WorkSpacesWeb::UserSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspacesweb-usersettings.html)

**Comment by kadrach** [comment]
Curiously these schemas have been available since late 2023, e.g. [here](https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/provider/generators/allschemas/available_schemas.2023-09-20.hcl#L3586), but have never made it into the defining [configuration file](https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/provider/all_schemas.hcl). I'm not entirely sure how the configuration file is created. While I have not actually tested these resources, the provider _can_ successfully generate resources for these if added to the configuration file.

**Comment by wellsiau-aws** [comment]
@dylanmtaylor , these resources was added on v 0.74.0 

I haven't tested it myself so I highly recommend to test it before using it in your workload.

I will close this issue now.
