### ISSUE TITLE
Request for Terraform for Six AWS APIs

### ISSUE THREAD

**Issue by mledwar** [hashicorp/terraform-provider-awscc#1467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

Please create new Terraform for the following six AWS APIs:

DescribeAssetBundleExportJob
(https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAssetBundleExportJob.html)

DescribeAssetBundleImportJob
(https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAssetBundleImportJob.html)

ListAssetBundleExportJobs
(https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ListAssetBundleExportJobs.html)

ListAssetBundleImportJobs
(https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ListAssetBundleImportJobs.html)

StartAssetBundleExportJob
(https://docs.aws.amazon.com/quicksight/latest/APIReference/API_StartAssetBundleExportJob.html)

StartAssetBundleImportJob
(https://docs.aws.amazon.com/quicksight/latest/APIReference/API_StartAssetBundleImportJob.html)

### New or Affected Resource(s)

awscc_describe_asset_bundle_export_job
awscc_describe_asset_bundle_import_job
awscc_list_asset_bundle_export_jobs
awscc_list_asset_bundle_import_jobs
awscc_start_asset_bundle_export_job
awscc_start_asset_bundle_import_job

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by breathingdust** [comment]
Hi @mledwar! This provider is generated from CloudFormation resource schemas. I do not see support for this in the CloudFormation registry:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_QuickSight.html

I would raise this with AWS to add support there.
