### ISSUE TITLE
[New Resource]: IoT Thing Group

### ISSUE THREAD

**Issue by PeterBurner** [hashicorp/terraform-provider-awscc#1471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

The `AWS::IoT::ThingGroup` resource is missing from the provider. Please add it.

### New or Affected Resource(s)

* awscc_iot_thing_group

### Potential Terraform Configuration

```hcl
resource "awscc_iot_thing_group" "parent" {
  name = "parent"
  properties {
    attribute_payload {
      attributes = {
        One = "11111"
        Two = "TwoTwo"
      }
    }
    description = "This is a parent thing group"
  }
  tags = [
    {
      Key = "Environment"
      Value = "dev"
    }
  ]
}

resource "awscc_iot_thing_group" "child" {
  name = "child"
  properties {
    attribute_payload {
      attributes = {
        One = "11111"
        Two = "TwoTwo"
      }
    }
    description = "This is a child thing group"
  }
  parent_group_name = awscc_iot_thing_group.parent.name
  tags = [
    {
      Key = "Environment"
      Value = "dev"
    }
  ]
}

resource "awscc_iot_thing_group" "dynamic" {
  name = "dynamic"
  properties {
    attribute_payload {
      attributes = {
        One = "11111"
        Two = "TwoTwo"
      }
    }
    description = "This is a dynamic thing group"
  }
  query = "attributes.temperature>60"
  tags = [
    {
      Key = "Environment"
      Value = "dev"
    }
  ]
}

data "awscc_iot_thing_group" "lookup" {
  name = "child"
}
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-thinggroup.html
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_group
* https://github.com/hashicorp/terraform-provider-aws/issues/28575

**Comment by breathingdust** [comment]
Resource generation is currently suppressed due to: #125

**Comment by PeterBurner** [comment]
Is resource generation in general blocked or specifically for this resource? @breathingdust

**Comment by breathingdust** [comment]
@PeterBurner there are a number of resources which our generation code is unable to handle currently, in those cases we suppress generation. Most resources are fine, its just those with specific schema representation.
