### ISSUE TITLE
v0.72.0 `awscc_ssm_document` Error: Unable to Convert Configuration

### ISSUE THREAD

**Issue by sh-dan** [hashicorp/terraform-provider-awscc#1485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version
Terraform v1.7.5 on darwin_arm64

provider registry.terraform.io/hashicorp/awscc v0.72.0

### Affected Resource(s)

* awscc_ssm_document

### Terraform Configuration Files

Just a single resource is enough to replicate: 

```hcl
terraform {
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.1"
    }
  }
}

resource "awscc_ssm_document" "appconfig_document" {
  name            = "Config-Doc"
  document_type   = "ApplicationConfiguration"
  document_format = "JSON"

  requires = [
    {
      name    = "Config-Schema-Doc"
      version = "$LATEST"
    }
  ]
  content = "{testBool: true}"
  }
```

### Debug Output

```
2024-03-21T12:19:41.769-0700 [ERROR] provider.terraform-provider-awscc_v0.72.0_x5: Response contains error diagnostic: @module=sdk.proto diagnostic_severity=ERROR diagnostic_summary="Unable to Convert Configuration" tf_resource_type=awscc_ssm_document tf_rpc=ValidateResourceConfig @caller=github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov6/internal/diag/diagnostics.go:58 tf_provider_addr=registry.terraform.io/hashicorp/awscc tf_req_id=99697b64-c892-169c-6103-2a1ad3e6ac74
  diagnostic_detail=
  | An unexpected error was encountered when converting the configuration from the protocol type. This is always an issue in terraform-plugin-framework used to implement the provider and should be reported to the provider developers.
  | 
  | Please report this to the provider developer:
  | 
  | Unable to unmarshal DynamicValue: AttributeName("requires").ElementKeyInt(0): error decoding object; expected 0 attributes, got 2
   tf_proto_version=6.4 timestamp=2024-03-21T12:19:41.769-0700
2024-03-21T12:19:41.769-0700 [ERROR] vertex "awscc_ssm_document.appconfig_document" error: Unable to Convert Configuration
╷
│ Error: Unable to Convert Configuration
│ 
│   with awscc_ssm_document.appconfig_document,
│   on main.tf line 12, in resource "awscc_ssm_document" "appconfig_document":
│   12: resource "awscc_ssm_document" "appconfig_document" {
│ 
│ An unexpected error was encountered when converting the configuration from the protocol type. This is always an issue in terraform-plugin-framework used to
│ implement the provider and should be reported to the provider developers.
│ 
│ Please report this to the provider developer:
│ 
│ Unable to unmarshal DynamicValue: AttributeName("requires").ElementKeyInt(0): error decoding object; expected 0 attributes, got 2

```
### Expected Behavior

When using awscc_ssm_document with a `requires` parameter
terraform plan and apply should work without errors

### Actual Behavior

 plan/apply fail with an error if the awscc provider version = v0.72.0
 v0.71.0 works as expected 

### Steps to Reproduce

1. `terraform apply`

**Comment by novekm** [comment]
Same issue is happening in #1486

**Comment by novekm** [comment]
This scope of this issue appears to apply to any resource where an Attributes List is defined. For example, see this configuration for `awscc_s3_bucket` that has `tags` (Attributes List) defined.

```
resource "awscc_s3_bucket" "example" {
  bucket_name = "kevon"

  tags = [{
    key   = "Name"
    value = "My bucket"
  }]

}
```

The same error is thrown:
```
│ Error: Unable to Convert Configuration
│ 
│   with awscc_s3_bucket.example,
│   on main.tf line 1, in resource "awscc_s3_bucket" "example":
│    1: resource "awscc_s3_bucket" "example" {
│ 
│ An unexpected error was encountered when converting the configuration from the protocol type. This is always an issue in terraform-plugin-framework used to implement the
│ provider and should be reported to the provider developers.
│ 
│ Please report this to the provider developer:
│ 
│ Unable to unmarshal DynamicValue: AttributeName("tags").ElementKeyInt(0): error decoding object; expected 0 attributes, got 2
```

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-awscc/pull/1463.
