### ISSUE TITLE
Not able to perform Update on AWS Lambda function

### ISSUE THREAD

**Issue by naveen-amzn** [hashicorp/terraform-provider-awscc#1679]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "awscc_lambda_function" "main" {
  function_name = "lambda_function_name"
  description   = "AWS Lambda function"
  code = {
    zip_file = <<EOF
def lambda_handler(event,context):
  print("Hello World!")
  return 
EOF
  }
  package_type  = "Zip"
  handler       = "main.lambda_handler"
  runtime       = "python3.10"
  timeout       = "300"
  memory_size   = "128"
  role          = awscc_iam_role.main.arn
  architectures = ["arm64"]
  environment = {
    variables = {
      MY_KEY_1 = "MY_VALUE_1"
      MY_KEY_2 = "MY_VALUE_2"
    }
  }
}
```

### Panic Output
![image](https://github.com/hashicorp/terraform-provider-awscc/assets/113793624/2cf778b6-23da-4f8f-8d04-4550b98d6685)

### Expected Behavior

After a successful apply, when we try to update lambda function and then again try to update then Lambda function should be updated successfully.
### Actual Behavior

After a successful apply, when we try to update lambda function it fails with with the below error.
![image](https://github.com/hashicorp/terraform-provider-awscc/assets/113793624/73105f81-e6dd-4fa8-bf19-ffed55f05fba)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by wellsiau-aws** [comment]
worth noting that `zip_file` is considered as writeOnlyProperties:
```
aws cloudformation describe-type --type RESOURCE --type-name AWS::Lambda::Function | jq -r ".Schema" | jq ".writeOnlyProperties"
[
  "/properties/SnapStart",
  "/properties/SnapStart/ApplyOn",
  "/properties/Code",
  "/properties/Code/ImageUri",
  "/properties/Code/S3Bucket",
  "/properties/Code/S3Key",
  "/properties/Code/S3ObjectVersion",
  "/properties/Code/ZipFile"
]
```

and #1737 might have fixed this problem

**Comment by wellsiau-aws** [comment]
Tested on Terraform AWSCC provider ver **1.4.0**:

```
awscc_iam_role.main: Refreshing state... [id=o1Znufrt8TmGudfikHlPQnMLp-OEk0XO7ffeXJ]
awscc_lambda_function.main: Refreshing state... [id=lambda_function_name]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # awscc_lambda_function.main will be updated in-place
  ~ resource "awscc_lambda_function" "main" {
      ~ code                           = {
          + image_uri         = (known after apply)
          + s3_bucket         = (known after apply)
          + s3_key            = (known after apply)
          + s3_object_version = (known after apply)
          ~ zip_file          = <<-EOT
                def lambda_handler(event,context):
              -   print("Hello World!")
              +   print("Hello World Wide Web!")
                  return
            EOT
        }
      + code_signing_config_arn        = (known after apply)
      + dead_letter_config             = (known after apply)
      + file_system_configs            = (known after apply)
        id                             = "lambda_function_name"
      + image_config                   = (known after apply)
      + kms_key_arn                    = (known after apply)
      + layers                         = (known after apply)
      + reserved_concurrent_executions = (known after apply)
      + tags                           = (known after apply)
      + vpc_config                     = (known after apply)
        # (17 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
awscc_lambda_function.main: Modifying... [id=lambda_function_name]
awscc_lambda_function.main: Still modifying... [id=lambda_function_name, 10s elapsed]
awscc_lambda_function.main: Modifications complete after 12s [id=lambda_function_name]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

I am going to close this as resolved.
