### ISSUE TITLE
awscc_mediaconnect_flow SRT max_latency default value

### ISSUE THREAD

**Issue by mnmozi** [hashicorp/terraform-provider-awscc#1704]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version
```bash
Terraform v1.5.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/awscc v0.76.0
```
### Affected Resource(s)

* awscc_mediaconnect_flow

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "awscc_mediaconnect_flow" "SRT_HORIZONTAL" {
  name = "srt_horizontal"
  source = {
    name           = "SRT"
    description    = "This flow stream with the SRT protocol"
    ingest_port    = 5000
    whitelist_cidr = "0.0.0.0/32"
    protocol       = "srt-listener"
  }
}

```

### Debug Output

https://gist.github.com/mnmozi/dfd480eba9a7765f87c401a30e0742e0

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

AWS MediaConnect does not accept max_latency for the SRT protocol, but Terraform sets it to a default value of 2000. 

### References

* #0000

**Comment by quixoticmonk** [comment]
Seems like a schema issue : 
- https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/service/cloudformation/schemas/AWS_MediaConnect_Flow.json#L71

**Comment by quixoticmonk** [comment]
The schema update is in place. Will need to test with the next schema refresh on provider.

**Comment by quixoticmonk** [comment]
@mnmozi Can you retest ? The schema refresh is in and I was able to test it once. 
```
 # awscc_mediaconnect_flow.SRT_HORIZONTAL will be created
  + resource "awscc_mediaconnect_flow" "SRT_HORIZONTAL" {
      + availability_zone      = (known after apply)
      + egress_ip              = (known after apply)
      + flow_arn               = (known after apply)
      + flow_availability_zone = (known after apply)
      + id                     = (known after apply)
      + maintenance            = (known after apply)
      + media_streams          = (known after apply)
      + name                   = "srt_horizontal"
      + source                 = {
          + decryption                         = (known after apply)
          + description                        = "This flow stream with the SRT protocol"
          + entitlement_arn                    = (known after apply)
          + gateway_bridge_source              = (known after apply)
          + ingest_ip                          = (known after apply)
          + ingest_port                        = 5000
          + max_bitrate                        = (known after apply)
          + max_latency                        = (known after apply)
          + max_sync_buffer                    = (known after apply)
          + media_stream_source_configurations = (known after apply)
          + min_latency                        = (known after apply)
          + name                               = "SRT"
          + protocol                           = "srt-listener"
          + sender_control_port                = (known after apply)
          + sender_ip_address                  = (known after apply)
          + source_arn                         = (known after apply)
          + source_ingest_port                 = (known after apply)
          + source_listener_address            = (known after apply)
          + source_listener_port               = (known after apply)
          + stream_id                          = (known after apply)
          + vpc_interface_name                 = (known after apply)
          + whitelist_cidr                     = "0.0.0.0/32"
        }
      + source_failover_config = (known after apply)
      + vpc_interfaces         = (known after apply)
    }
```

**Comment by mnmozi** [comment]
I just tested it, and it's working. Thank you for the fix.

**Comment by quixoticmonk** [comment]
Thanks @mnmozi . Closing the issue with your note.
