### ISSUE TITLE
awscc_msk_cluster: cluster creation fails when optional log_group field omitted

### ISSUE THREAD

**Issue by quixoticmonk** [hashicorp/terraform-provider-awscc#1776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

```
terraform -v
Terraform v1.8.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.51.1
+ provider registry.terraform.io/hashicorp/awscc v1.0.0
```

### Affected Resource(s)

* awscc_msk_cluster

### Terraform Configuration Files

Configuration below.

```hcl
resource "awscc_msk_cluster" "example" {
  cluster_name           = "example"
  kafka_version          = "3.5.1"
  number_of_broker_nodes = 4
  broker_node_group_info = {
    broker_az_distribution = "DEFAULT"
    client_subnets         = ["subnet-08ad4f216501972ec", "subnet-0a4649033661b7a3e"]
    instance_type          = "kafka.m7g.large"
    security_groups        = ["sg-044b064d6706ce34f"]
  }
  encryption_info = {
    encryption_in_transit = {
      client_broker = "TLS_PLAINTEXT"
      in_cluster    = true
    }
  }
  enhanced_monitoring = "PER_TOPIC_PER_BROKER"
  storage_mode        = "LOCAL"

  logging_info = {
    broker_logs = {
      cloudwatch_logs = {
        enabled = true
      }
    }
  }

  tags = {
    "Modified By" = "AWSCC"
  }
}

```

### Expected Behavior

* Expected the cluster to be created.

### Actual Behavior

The `log_group` in the `broker_logs` is optional in the schema. Terraform apply fails on cluster creation with the below message:

```
╷
│ Error: AWS SDK Go Service Operation Incomplete
│
│   with awscc_msk_cluster.example,
│   on main.tf line 1, in resource "awscc_msk_cluster" "example":
│    1: resource "awscc_msk_cluster" "example" {
│
│ Waiting for Cloud Control API service CreateResource operation completion returned: waiter
│ state transitioned to FAILED. StatusMessage: [ClientRequestToken:
│ ed77747b-52ee-4312-873d-b0546d059d96] To use CloudWatch Logs as a destination for broker
│ logs, you must specify a CloudWatch log group. (Service: Kafka, Status Code: 400, Request
│ ID: 71d16ac8-63fd-410e-8758-1e0c7c7fec29) 'brokerLogs'. ErrorCode: InvalidRequest
```

### Steps to Reproduce

1. `terraform apply`

**Comment by wellsiau-aws** [comment]
@quixoticmonk , I believe it was marked as optional since the behavior is driven by other attribute `cloudwatch_log.enabled` = `true` / `false`.

In case when you specify it as `false, log group name is not required.
In case when you specify it as `true`, then the log group name is required.

**Comment by wellsiau-aws** [comment]
@quixoticmonk , let me know if you able to replicate the problem when you specify `cloudwatch_log.enabled` = `false` ?

**Comment by quixoticmonk** [comment]
@wellsiau-aws That seems to be the behavior and I can create cluster with the below log info block. It does seem to be 

```
  logging_info = {
    broker_logs = {
      cloudwatch_logs = {
        enabled = false
      }
    }
  }

```

It does seem to have the subsequent apply issue. Will review it further and tag it to any of our open issues.

```
~ resource "awscc_msk_cluster" "example" {
    + client_authentication  = (known after apply)
      id                     = "arn:aws:kafka:us-east-1:############:cluster/example/9e9120ad-896c-409a-a05a-1e753df06d71-7"
    ~ logging_info           = {
        ~ broker_logs = {
            ~ cloudwatch_logs = {
                + log_group = (known after apply)
                  # (1 unchanged attribute hidden)
              }
              # (2 unchanged attributes hidden)
          }
      }
      tags                   = {
          "Modified By" = "AWSCC"
      }
      # (11 unchanged attributes hidden)
  }

```
