### ISSUE TITLE
Support for 'darwin_arm64' the Apple Macbooks

### ISSUE THREAD

**Issue by maanisim** [hashicorp/terraform-provider-awscc#1789]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_1

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.1.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.1.0"
    }
  }
}


provider "aws" {
  region = var.aws_region
}

resource "aws_kms_key" "terraform" {
  description = "Example key for Cassandra table"
}

provider "awscc" {
  region = var.aws_region
}

provider "random" {}
```

### Expected Behavior

When following https://developer.hashicorp.com/terraform/tutorials/aws/aws-cloud-control 
`terraform init` should work as expected after adding the awscc provider, this is not currently the case. 

### Actual Behavior

```
user@host learn-terraform-aws-cloud-control % terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/awscc versions matching "~> 0.1.0"...
- Finding hashicorp/random versions matching "~> 3.1.0"...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v3.59.0
- Installing hashicorp/random v3.1.3...
- Installed hashicorp/random v3.1.3 (signed by HashiCorp)
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/awscc v0.1.0 does not have a package
│ available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
```

### Steps to Reproduce

1. `terraform init`

### References

* https://github.com/hashicorp/terraform-provider-awscc/issues/320 mentions similar behaviour

**Comment by quixoticmonk** [comment]
@maanisim thank you for opening the issue.  Did you mean `"~> 0.1.0"` or `"~> 1.0.0"` in your awscc versions ? Can you update the version constraint and try ?

**Comment by maanisim** [comment]
Hi, @quixoticmonk the suggested fix indeed worked!

The docs in https://developer.hashicorp.com/terraform/tutorials/aws/aws-cloud-control are inaccurate.

**Comment by quixoticmonk** [comment]
This should be updated with https://github.com/hashicorp/terraform-provider-awscc/pull/1802.
