### ISSUE TITLE
Query on Support for Pod-Level Actions in EKS Clusters via AWS FIS

### ISSUE THREAD

**Issue by khizar43** [hashicorp/terraform-provider-awscc#1816]
Dear Terraform Support Team,

I hope this message finds you well. I am currently working on managing AWS resources using Terraform, specifically exploring the capabilities of AWS Fault Injection Simulator (FIS) for conducting actions at the pod level within EKS clusters.

According to AWS FIS documentation (https://docs.aws.amazon.com/fis/latest/userguide/eks-pod-actions.html), pod-level actions are supported, allowing actions such as CPU or memory stress to be applied directly to pods within an EKS cluster.

However, when attempting to define such actions using Terraform with the AWS provider (hashicorp/awscc), I encountered an error indicating that Terraform expected target types like "Cluster" or "Nodegroups," rather than "Pods."

Could you please clarify if Terraform currently supports defining actions at the pod level within EKS clusters using AWS FIS? If not, are there any plans to add support for this feature in future updates?

Your assistance in clarifying this matter would be greatly appreciated.

Thank you for your attention to this inquiry.

Best regards,

Here is my terraform file for creating AWS FIS experiment template 

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }

  required_version = ">= 1.2.0"
}

provider "aws" {
  region = "ap-south-1"
  profile = "saml"
}

# Create an IAM role for FIS with necessary permissions
resource "aws_iam_role" "fis_role" {
  name = "examplerole"

  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Effect = "Allow",
        Principal = {
          Service = "fis.amazonaws.com"
        },
        Action = "sts:AssumeRole"
      }
    ]
  })
}

resource "aws_iam_role_policy" "fis_role_policy" {
  role = aws_iam_role.fis_role.id

  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Effect = "Allow",
        Action = [
          "eks:DescribeCluster",
          "eks:ListClusters",
          "eks:ListNodegroups",
          "eks:DescribeNodegroup",
          "eks:ListUpdates",
          "eks:DescribeUpdate",
          "eks:ListFargateProfiles",
          "eks:DescribeFargateProfile",
          "ec2:DescribeInstances",
          "ec2:DescribeInstanceStatus",
          "ec2:SendDiagnosticInterrupt",
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
          "logs:DescribeLogGroups",
          "logs:DescribeLogStreams"
        ],
        Resource = "*"
      }
    ]
  })
}

# Define the FIS experiment template
resource "aws_fis_experiment_template" "example" {
  description = "AWS-FIS-example"
  role_arn    = "xxxx"

 

  action {
    name        = "EKS_Association_CPU-stress"
    action_id   = "aws:eks:pod-cpu-stress"
    description = "EKS_Association_CPU-stress"

    parameter {
      key   = "duration"
      value = "PT1M"
    }
    parameter {
      key   = "kubernetesServiceAccount"
      value = "fisserviceaccount"
    }
    parameter {
      key   = "percent"
      value = "100"
    }
    parameter {
      key   = "workers"
      value = "1"
    }

    target {
      key   = "Pods"
      value = "Pods-Target-1"
    }
  }

  action {
    name        = "Memory_stress"
    action_id   = "aws:eks:pod-memory-stress"
    description = "Memory_stress"

    parameter {
      key   = "duration"
      value = "PT1M"
    }
    parameter {
      key   = "kubernetesServiceAccount"
      value = "fisserviceaccount"
    }
    parameter {
      key   = "percent"
      value = "50"
    }

    target {
      key   = "Pods"
      value = "Pods-Target-1"
    }

    start_after = ["EKS_Association_CPU-stress"]
  }

  stop_condition {
    source = "none"
  }
  
   target {
    name          = "Pods-Target-1"
    resource_type = "aws:eks:pod"
    selection_mode = "ALL"

  #  parameters = {
    #  clusterIdentifier = "xxxx"
    #  namespace         = "aws-fis"
    #  selectorType      = "labelSelector"
    #  selectorValue     = "app=nginx"
   # }

    # Optional fields
    # filter can be used to select resources based on specific attributes
    # filter {
    #   key    = "attribute"
    #   value  = "attribute-value"
    # }

    # Specify the ARNs of the resources to target
    resource_arns = xxxx

    # Tags the resources need to have to be considered a valid target
    resource_tag {
      key   = "namespace"
      value = "aws-fis"
     }
    resource_tag {
      key  = "selectorType"
      value = "labelSelector"
     }
    resource_tag {
      key  = "selectorValue"
      value  = "app=nginx"
     }
  }

 # log_configuration {
 #   cloudwatch_logs_configuration {
 #     log_group_arn = "arn:aws:logs:ap-south-1:701971835315:log-group:FIS_perinatal_experiments:*"
  #  }
 #   log_schema_version = 2
#  }

  tags = {
    Name = "FIS_Perinatal_Experiments"
  }

 # experiment_options {
 #   account_targeting = "single-account"
 #   empty_target_resolution_mode = "fail"
 # }
}

output "fis_template_id" {
  value = aws_fis_experiment_template.Perinatal_MPS_Poc_India.id
}

ERROR: 

Error: expected action.0.target.0.key to be one of [Cluster Clusters DBInstances Instances Nodegroups Roles SpotInstances Subnets], got Pods
│
│   with aws_fis_experiment_template.EXAMPLE,
│   on main.tf line 19, in resource "aws_fis_experiment_template" "EXAMPLE":
│   19: resource "aws_fis_experiment_template" "EXAMPLE" {
│
╵
╷
│ Error: expected action.1.target.0.key to be one of [Cluster Clusters DBInstances Instances Nodegroups Roles SpotInstances Subnets], got Pods
│
│   with aws_fis_experiment_template.EXAMPLE,
│   on main.tf line 19, in resource "aws_fis_experiment_template" "EXAMPLE":
│   19: resource "aws_fis_experiment_template" "EXAMPLE" {

**Comment by quixoticmonk** [comment]
Hi @khizar43 , the resource `aws_fis_experiment_template` is part of the AWS provider and not AWSCC provider. Did you intend to open the issue on the [AWS provider](https://github.com/hashicorp/terraform-provider-aws) by any chance ?

Have you tried with [awscc_fis_experiment_template](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/fis_experiment_template) ?

**Comment by quixoticmonk** [comment]
@khizar43 AWSCC resource supports EKS pods. Tested with the below template with AWSCC provider. Note that the I have only tested the feasibility of using the action_id and resource_type in the resource. It would need to be modified according to your EKS cluster and experiment.

```
resource "awscc_fis_experiment_template" "example" {
  description = "example"
  role_arn    = "arn:aws:iam:::role/service-role/2123123"

  tags = {
    "Name" = "example"
  }

  stop_conditions = [{
    source = "none"
  }]

  actions = {
    action_1 = {
      name        = "EKS_Association_CPU-stress"
      action_id   = "aws:eks:pod-cpu-stress"
      description = "example action"
      parameters = {
        "kubernetesServiceAccount" : "myserviceaccount",
        "duration" : "PT5M",
      }
      targets = {
        "Pods" = "target1"
      }
    }
  }


  targets = {
    target1 = {
      name           = "example-target"
      resource_type  = "aws:eks:pod"
      selection_mode = "COUNT(3)"
      parameters = {
        "clusterIdentifier" : "mycluster",
        "namespace" : "default",
        "selectorType" : "labelSelector",
        "selectorValue" : "mylabel=mytarget",
      }

    }
  }

  experiment_options = {
    empty_target_resolution_mode = "fail"
  }

}


```

**Comment by khizar43** [comment]
@quixoticmonk  Thank you for your response. Your template worked perfectly for me. I tested the feasibility of using the action_id and resource_type with EKS pods, and it was successful. I appreciate your assistance!

**Comment by quixoticmonk** [comment]
Closing the issue based on the resolution comment above.
