### ISSUE TITLE
awscc_lightsail_certificate: Dummy resource description presumably obtained from CloudFormation schema

### ISSUE THREAD

**Issue by acwwat** [hashicorp/terraform-provider-awscc#1820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* `awscc_lightsail_certificate`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

The [resource documentation](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lightsail_certificate) should show a proper description, such as:

> Resource Type definition for AWS::Lightsail::Certificate

### Actual Behavior

The [resource documentation](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lightsail_certificate) is showing what seems to be a dummy description, presumably obtained from the CloudFormation schema:

> An example resource schema demonstrating some basic constructs and validation rules.

### Steps to Reproduce

1. Check the description in the [resource documentation](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lightsail_certificate)

### Important Factoids

n/a

### References

n/a

**Comment by quixoticmonk** [comment]
Thank you for opening the issue @acwwat . The documentation is generated automatically from the CFN Schema for the resource the provider ingests. I have opened a PR to update the description of the `AWS::Lightsail::Certificate` resource.

**Comment by godduv-amzn** [comment]
This issue has been fixed and merged in this PR: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-lightsail/pull/70.

**Comment by quixoticmonk** [comment]
Closing the issue based on the documentation update.
![Screenshot 2024-07-26 at 10 25 38](https://github.com/user-attachments/assets/a2a9860c-8386-40a9-a8a0-4e4fd34101ae)
