### ISSUE TITLE
awscc_lightsail_alarm: Wrong description for the `monitored_resource_name` argument

### ISSUE THREAD

**Issue by acwwat** [hashicorp/terraform-provider-awscc#1821]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* `awscc_lightsail_alarm`

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

The [resource documentation](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lightsail_alarm) should show a proper description for the `monitored_resource_name` argument, such as what's in the [API reference](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_PutAlarm.html#Lightsail-PutAlarm-request-monitoredResourceName):

>The name of the Lightsail resource that will be monitored.
>
>Instances, load balancers, and relational databases are the only Lightsail resources that can currently be monitored by alarms.

Resource Type definition for AWS::Lightsail::Certificate

### Actual Behavior

The [resource documentation](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lightsail_certificate) has an unrelated description for the `monitored_resource_name`:

>The validation status of the SSL/TLS certificate.

### Steps to Reproduce

1. Check the description of the `monitored_resource_name` argument in the [resource documentation](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lightsail_certificate)

### Important Factoids

n/a

### References

n/a

**Comment by quixoticmonk** [comment]
Thank you for opening the issue @acwwat . I have opened a PR on the lightsail providers documentation to fix this.

**Comment by godduv-amzn** [comment]
This issue has been fixed and merged in this PR: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-lightsail/pull/70.

**Comment by quixoticmonk** [comment]
Closing this issue based on the documentation update below.
![Screenshot 2024-07-26 at 10 24 20](https://github.com/user-attachments/assets/06203976-a35a-40e2-96e6-d4db00d83267)
