### ISSUE TITLE
No changes. Your infrastructure matches the configuration.

### ISSUE THREAD

**Issue by Waqiah** [hashicorp/terraform-provider-awscc#1856]
When following 
https://aws.amazon.com/blogs/devops/quickly-adopt-new-aws-features-with-the-terraform-aws-cloud-control-provider/
https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/data-sources/resourcegroups_group

Not able to retrieve group resources from the data source for arn:aws:resource-groups:us-east-1:123456789123:group/sandbox_ou

When running terraform apply:
$ terraform apply
data.awscc_resourcegroups_group.this: Reading...
data.awscc_resourcegroups_group.this: Read complete after 1s [id=sandbox_ou]

But received the output:
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:

this = {
  "arn" = "arn:aws:resource-groups:us-east-1:123456789123:group/sandbox_ou"
  "configuration" = tolist(null) /* of object */
  "description" = "sandbox OUs"
  "id" = "sandbox_ou"
  "name" = "sandbox_ou"
  "resource_query" = {
    "query" = {
      "resource_type_filters" = tolist([
        "AWS::Organizations::OrganizationalUnit",
      ])
      "stack_identifier" = tostring(null)
      "tag_filters" = tolist([
        {
          "key" = "environment"
          "values" = tolist([
            "sandbox",
          ])
        },
      ])
    }
    "type" = "TAG_FILTERS_1_0"
  }
  "resources" = tolist(null) /* of string */
  "tags" = tolist(null) /* of object */
}

The resources are returned as null.

-----------------------------------
Template file:

terraform {
  required_version = ">= 0.15"
  required_providers {
    awscc = {
      source = "hashicorp/awscc"
      version = ">=1.4.0"
    }
  }
}

provider "awscc" {
  region = "us-east-1"
}

data awscc_resourcegroups_group this {
  id = "sandbox_ou"
}

output "this" {
  value = data.awscc_resourcegroups_group.this
}

**Comment by quixoticmonk** [comment]
Thank you for opening the issue @Waqiah . CloudControl API for the type `AWS::ResourceGroups::Group` returns

```
aws cloudcontrol get-resource --type-name AWS::ResourceGroups::Group --identifier s3group
{
    "TypeName": "AWS::ResourceGroups::Group",
    "ResourceDescription": {
        "Identifier": "s3group",
        "Properties": "{\"ResourceQuery\":{\"Type\":\"TAG_FILTERS_1_0\",\"Query\":{\"TagFilters\":[{\"Values\":[\"manu\"],\"Key\":\"created_by\"}],\"ResourceTypeFilters\":[\"AWS::S3::Bucket\"]}},\"Arn\":\"arn:aws:resource-groups:us-east-1:############:group/s3group\",\"Tags\":[],\"Name\":\"s3group\"}"
    }
}

```

**Comment by quixoticmonk** [comment]
Opened an internal ticket to review this.

**Comment by wellsiau-aws** [comment]
after consulting with service team, we understand that the `Resources` property is not expected to be populated with the list of resource ARNs in the response to **tag-based resource groups**. 

Instead, it's used as a property for the list of ARNs of AWS resources that you want to add to **service-linked groups** (when the `Configuration` property is also set).

to achieve your objective, we need to use (GetGroupQuery)[https://docs.aws.amazon.com/ARG/latest/APIReference/API_GetGroupQuery.html], unfortunately there is not AWSCC resource for this particular API today.

**Comment by wellsiau-aws** [comment]
I will go ahead and close this issue, please free free to re-open if you have follow up questions.
