### ISSUE TITLE
The terraform-provider-awscc_v1.4.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by jinsi14** [hashicorp/terraform-provider-awscc#1870]
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more 
│ details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-awscc_v1.4.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xc pc=0xace03a]

goroutine 16 [running]:
github.com/hashicorp/terraform-provider-awscc/internal/generic.(*genericResource).Create(0x6840780, {0x2ff07e4, 0x5d20720}, {{{{0x2ff2cf4, 0x5d20bb8}, {0x1f58e00, 0x6c1b980}}, {0x30097a0, 0x4f90030}}, {{{0x2ff2cf4, ...}, ...}, ...}, ...}, ...)
        github.com/hashicorp/terraform-provider-awscc/internal/generic/resource.go:397 +0x83a
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x4ebc148, {0x2ff07e4, 0x5d20720}, 0x6c6ba80, 0x6c6ba6c)
        github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_createresource.go:101 +0x56b
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x4ebc148, {0x2ff07e4, 0x5d20720}, 0x5a5ec00, 0x6c6bb20)
        github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_applyresourcechange.go:57 +0x409
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x4ebc148, {0x2ff07e4, 0x5d206f0}, 0x5a5eba0)  
        github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_applyresourcechange.go:55 +0x461
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x4eb60f0, {0x2ff07e4, 0x5d20438}, 0x5fb7000)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x439
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x204f720, 0x4eb60f0}, {0x2ff07e4, 0x5d20438}, 0x5fb6fc0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x4ebc008, {0x2ff07e4, 0x5d20408}, {0x3008568, 0x4dfe5a8}, 0x4c9b3f8, 0x4eba180, 0x3d8574c, 0x0)  
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf44
google.golang.org/grpc.(*Server).handleStream(0x4ebc008, {0x3008568, 0x4dfe5a8}, 0x4c9b3f8)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x10cf
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xaa
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 21
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x12f

Error: The terraform-provider-awscc_v1.4.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jinsi14** [comment]
Please help to resolve error.
Error: The terraform-provider-awscc_v1.4.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by quixoticmonk** [comment]
Thank you for opening the issue @jinsi14 . Can you provide some more details ?

- Was this seen during an upgrade of the provider?
-  Is this an intermittent issue or something you can reproduce consistently?

**Comment by michaljancek** [comment]
@jinsi14 I just had similar issue (same error) with awscc_v1.6.0. I enabled Terraform debug with TF_LOG=DEBUG and found that awscc plugin was crashing on missing permissions. Maybe you can see something useful in debug?

**Comment by wellsiau-aws** [comment]
@michaljancek , @jinsi14 , thanks for reporting this issue.

Can you clarify if is this only happening on specific AWS CC resources?
