### ISSUE TITLE
awscc_cleanrooms_configured_table_association import fails at validation stage

### ISSUE THREAD

**Issue by kkonstant-in** [hashicorp/terraform-provider-awscc#1881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.9.1
hashicorp/aws = 5.58.0

### Affected Resource(s)

* awscc_cleanrooms_configured_table_association

### Terraform Configuration Files

I think this TF code is not related to the issue, but I provide it just in case

```hcl
resource "awscc_cleanrooms_configured_table_association" "customer_data" {
    configured_table_identifier = awscc_cleanrooms_configured_table.tvnz.id
    membership_identifier       = awscc_cleanrooms_membership.turners_collab.id
    name                        = aws_glue_catalog_table.customer_data.name
    role_arn                    = aws_iam_role.cleanrooms_table_query.arn
}
```

### Debug Output
![table_association](https://github.com/user-attachments/assets/d00bf459-0861-445f-bd63-180da3b66e7f)

### Expected Behavior

The table_association should be imported

### Actual Behavior

The actual configuredTableAssociation ID does not pass validation check

### Steps to Reproduce

I'm trying to do the import and get the error

1. Check the association_id `aws cleanrooms get-configured-table-association --configured-table-association-identifier 804f203e-33c5-4ecc-9898-b1cf5b96e7e8 --membership-identifier ed969fc4-0fd2-4815-955b-7373833b3542`
2. Try to import the resource `terraform import awscc_cleanrooms_configured_table_association.customer_data 804f203e-33c5-4ecc-9898-b1cf5b96e7e8`

### References

The import was done according to the docs here: https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/cleanrooms_configured_table_association

**Comment by kkonstant-in** [comment]
Hi, may I have any update for this issue please?

**Comment by quixoticmonk** [comment]
Thank you for opening the issue @kkonstant-in . I am able to reproduce this with a datasource as well. Let me open an internal ticket to review this behavior.

**Comment by kkonstant-in** [comment]
Hi @quixoticmonk , many thanks for the tip.

In my case the ordering was different `configured_table_identifier|membership_identifier` and it definitely worked well.
I would never be able to guess it from the error output without your help: `is not valid for identifier [/properties/ConfiguredTableAssociationIdentifier, /properties/MembershipIdentifier]`. Trust me, I tried different ways 😆 

Is it possible to make the output or [docs](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/cleanrooms_configured_table_association) more clear? 😇 

Thank you so much for the clarification!

**Comment by quixoticmonk** [comment]
Yeah , you are correct. I had the order mixed up. its  `configured_table_association_identifier| membership_identifier` or `configured_table_identifier|membership_identifier `.  I can take that feedback to the team on the description of `id` as this comes from the registry schema for the resource here.

**Comment by kkonstant-in** [comment]
Thank you very much for your help!
From my side the issue is resolved. Feel free to close it or choose any other way which makes the most sense to you.

**Comment by quixoticmonk** [comment]
Closing based on the comments above.
