### ISSUE TITLE
Upgrading awscc provider to anything more than 1.0.0 creates a new change in awscc_chatbot_slack_channel_configuration and times out on apply

### ISSUE THREAD

**Issue by trixobird** [hashicorp/terraform-provider-awscc#1882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

```
Terraform v1.9.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.58.0
+ provider registry.terraform.io/hashicorp/awscc v1.5.0
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/tfe v0.57.0
+ provider registry.terraform.io/vercel/vercel v1.12.0
```

### Affected Resource(s)

awscc_chatbot_slack_channel_configuration

### Terraform Configuration Files

The whole repo is [open sourced](https://github.com/adsviewer/turboviewer). [This](https://github.com/adsviewer/turboviewer/blob/58c3e7c8a88eac4b88ac98e29b5d79b932b632b3/infrastructure/modules/environment/slack.tf#L1-L8) is the file in question 
```hcl
resource "awscc_chatbot_slack_channel_configuration" "error_slack_channel_configuration" {
  configuration_name = "${var.environment}-slack-channel-config"
  iam_role_arn       = awscc_iam_role.slack_assume_role.arn
  logging_level      = "ERROR"
  slack_channel_id   = "errors"
  slack_workspace_id = var.slack_workspace_id
  sns_topic_arns     = [module.server.sns_app_runner_error_topic_arn, aws_sns_topic.channel_ingress_error_topic.arn]
}
```

### Debug Output

https://app.terraform.io/app/adsviewer/workspaces/prod/runs/run-qEuDcbfRK2bNQ5Ge

### Expected Behavior

There should be no changes in the configuration

### Actual Behavior

There was a change in `module.environment.awscc_chatbot_slack_channel_configuration.error_slack_channel_configuration` due to 

```
no-op
id :
"arn:aws:chatbot::***:chat-configuration/slack-channel/prod-slack-channel-config"
```

### What happened

I upgraded hashicorp/awscc version from 1.0.0 to 1.5.0 and I noticed that instead of no changes had this change in `awscc_chatbot_slack_channel_configuration`. When I tried to apply the process timed out after 2h. I am using terraform cloud so you should have access to the whole run.

I tried upgrading to 1.2.0, 1.3, 1.4 the same result, the plan had a new change. In 1.1.0 there was an error during the plan, you may find it here: https://app.terraform.io/app/adsviewer/workspaces/prod/runs/run-yzbys9PEebTRTfeo

**Comment by quixoticmonk** [comment]
Thank you for opening the issue @trixobird. Is your issue similar to https://github.com/hashicorp/terraform-provider-awscc/issues/1841 ? Unfortunately, I cannot see your HCP Terraform workspace runs.

Is the slack channel id in your configuration correct ? `slack_channel_id   = "errors"` . This should be the channel_id which is usually a 9 char string.

**Comment by trixobird** [comment]
> Thank you for opening the issue @trixobird. Is your issue similar to #1841 ? Unfortunately, I cannot see your HCP Terraform workspace runs.
> 
> Is the slack channel id in your configuration correct ? `slack_channel_id = "errors"` . This should be the channel_id which is usually a 9 char string.

yes this is exactly the same, apologies for opening a new one. I did see it, but for some reason my mind didn't register it :'(
