### ISSUE TITLE
awscc_fis_experiment_template Issues with ASG parameter: availabilityzoneIdentifiers

### ISSUE THREAD

**Issue by junkeiro** [hashicorp/terraform-provider-awscc#2003]
### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform version: 1.9.0
awscc version: 1.13.0

### Affected Resource(s)

* awscc_fis_experiment_template

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```terraform
resource "awscc_fis_experiment_template" "fis_ec2Fis" {
  description = "Dynamic FIS EC2"
  role_arn    = aws_iam_role.iam_ec2Fis.arn

  actions = {
    "TEAM-EC2-action" = {
      name        = "TEAM-EC2-action"
      action_id   = "aws:ec2:asg-insufficient-instance-capacity-error"
      description = "EC2 Dynamic FIS by tf-fis-modules"

      targets = {
        AutoScalingGroups = "TEAM-EC2-target"
      }

      parameters = {
        "availabilityzoneIdentifiers" = "usw2-az1"
        "duration"                    = "PT10M"
        "percentage"                  = "100"
      }
    }
  }
...
...
```

#### TERRAFORM PLAN Succeeding shows:
```shell
resource "awscc_fis_experiment_template" "fis_ec2Fis" {
      + actions                = {
          + "TEAM-EC2-action" = {
              + action_id   = "aws:ec2:asg-insufficient-instance-capacity-error"
              + description = "EC2 Dynamic FIS"
              + parameters  = {
                  + "availabilityzoneIdentifiers" = "usw2-az1"
                  + "duration"                    = "PT10M"
                  + "percentage"                  = "100"
                }
              + start_after = (known after apply)
            }
............
```

#### TERRAFORM APPLY ignoring the availabilityZoneIdentifiers parameter:
```shell
│ Error: AWS SDK Go Service Operation Incomplete
│ 
│   with awscc_fis_experiment_template.fis_ec2Fis,
│   on main.tf line 13, in resource "awscc_fis_experiment_template" "fis_ec2Fis":
│   13: resource "awscc_fis_experiment_template" "fis_ec2Fis" {
│ 
│ Waiting for Cloud Control API service CreateResource operation completion
│ returned: waiter state transitioned to FAILED. StatusMessage: Missing value
│ for required parameter "availabilityZoneIdentifiers" in action
│ "TEAM-EC2-action". (Service: AWSFIS; Status Code: 400; Error Code:
│ ValidationException; Request ID: xxxxxx-xxxxxxxxxxxx-xxxxxx;
│ Proxy: null). ErrorCode: InvalidRequest
```

### Expected Behavior

Terraform apply not having issues with the parameter: availabilityzoneIdentifiers

### Actual Behavior

Terraform apply phase isn't including the value of availabilityzoneIdentifiers parameter

### Steps to Reproduce

1. `terraform init`
2.  Use the provider either 'aws' or 'awscc' to create the resource `aws_fis_experiment_template` or `awscc_fis_experiment_template`
3.  Have in `action_id` the value `'aws:ec2:asg-insufficient-instance-capacity-error'`
4.  Provide at least the parameters `availabilityzoneIdentifiers` and `duration` (use reference links)
5. `terraform apply`

### Important Factoids

As mentioned before, terraform plan is passing successfully showing the parameters correctly. Terraform apply seems to be ignoring `availabilityzoneIdentifiers` parameter thus throws error.

### References

[FIS ASG Action](https://docs.aws.amazon.com/fis/latest/userguide/fis-actions-reference.html#asg-ice)
[Terraform AWSCC fis_experiment_template](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/fis_experiment_template)

**Comment by quixoticmonk** [comment]
Should it be `availabilityZoneIdentifiers` ?

**Comment by quixoticmonk** [comment]
Confirmed with the service team that the parameter key should be `availabilityZoneIdentifiers`. Please retest the deployment with the camel case input.

**Comment by junkeiro** [comment]
Thanks a lot for the tip, it worked!! I didn't see that "Z" in uppercase in the Terraform apply phase.
Is there any place in the documenation to know about that?, neither AWS or Terraform has this parameter specified at API call level.

**Comment by quixoticmonk** [comment]
Documentation will be updated soon based on the feedback I received. As a rule of thumb, these parameters will be camelCased.

**Comment by quixoticmonk** [comment]
Documentation has been updated to reflect the camelCased keys. Closing the issue based on this. Please re-open if you the issue has not been resolved.
