### ISSUE TITLE
v1.6.0 changes to assume_role is a breaking change. Should this be a major version bump as opposed to a minor version upgrade?

### ISSUE THREAD

**Issue by shashanklmurthy** [hashicorp/terraform-provider-awscc#2041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

awscc version - 1.6.0

### Affected Resource(s)

Changes to `assume_role` attribute in the provider configuration from object to list(object) is a breaking change and breaks provider versions pinned at `~> 1.0`

For example this configuration breaks due to the `assume_role` now being an array of roles 
```hcl

terraform {
  required_version = ">= 0.15.1"

  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 1.0"
    }
  }
}

provider "awscc" {
  region = "us-east-1"
  assume_role = {
    role_arn    = "xxxxRole""
  }
}

```

Should breaking versions be a major version bump instead? 

I noticed that you don't bump patch versions and only do minor version updates. 

I would still like to have the provider be updated with the latest resources introduced so I wouldn't want to pin my provider to a specific minor version  - any breaking change causes all modules that use the `awscc` provider to fail and we are using this extensively across our codebase.

**Comment by Jpk518** [comment]
@ewbankkit @gdavison this has to be considered a major bug here correct? This change breaks all existing implementations https://github.com/hashicorp/terraform-provider-awscc/pull/2029

The documentation isn't even updated to show this https://github.com/hashicorp/terraform-provider-awscc/blob/main/docs/index.md#assume-role

**Comment by breathingdust** [comment]
Apologies for the disruption, this was a miss on our part. We are organizing a patch release.
