### ISSUE TITLE
Add URI validation

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-awscc#205]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the Cloudformation Open Coverage Roadmap.

### Description

The `AWS:::S3::Bucket` resource type schema declares

```
        "WebsiteURL": {
            "description": "The Amazon S3 website endpoint for the specified bucket.",
            "examples": [
                "Example (IPv4): http://mystack-mybucket-kdwwxmddtr2g.s3-website-us-east-2.amazonaws.com/",
                "Example (IPv6): http://mystack-mybucket-kdwwxmddtr2g.s3.dualstack.us-east-2.amazonaws.com/"
            ],
            "format": "uri",
            "type": "string"
        }
```

For expediency, in #203 we ignored the [`uri` format](https://json-schema.org/understanding-json-schema/reference/string.html#resource-identifiers) value.
Add an attribute validator for this format.

**Comment by PatMyron** [comment]
curious about the rationale for [reimplementing these validations one-by-one](https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/provider/generators/shared/codegen/emitter.go) rather than using an [existing JSON schema validator](https://json-schema.org/implementations.html#validator-go)

**Comment by ewbankkit** [comment]
@PatMyron That is so we can perform the validation during `terraform plan`, before the CloudFormation resource model is created or submitted.

**Comment by ewbankkit** [comment]
```console
% grep '"format"' internal/service/cloudformation/schemas/*.json | grep uri
internal/service/cloudformation/schemas/AWS_S3_Bucket.json:            "format": "uri",
```
