### ISSUE TITLE
Terraform - dynamodb deletion_protection_enabled option not working

### ISSUE THREAD

**Issue by Dotisandhyarani** [hashicorp/terraform-provider-awscc#2053]
I have aws provider 
```
required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.67.0"
    }
}
```

Wanted to enable the `deletion_protection_enabled` option for the dynamo db table. But am getting below error
```
`╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/sd_test_table/aws/dynamodb/tables.tf line 11, in resource "aws_dynamodb_table" "dynamo_table":
│   11:   deletion_protection_enabled = var.deletion_protection_enabled
│ 
│ An argument named "deletion_protection_enabled" is not expected here.
`
```

Any help?

**Comment by quixoticmonk** [comment]
@Dotisandhyarani From the resource name `aws_dynamodb_table`, this should be opened against https://github.com/hashicorp/terraform-provider-aws repository. 

When you open the issue there, please provide the configuration you are using as well.

**Comment by Dotisandhyarani** [comment]
@quixoticmonk sure, I did. Thanks!

**Comment by quixoticmonk** [comment]
Closing the issue as the issue referenced is on aws provider.
