### ISSUE TITLE
 The terraform-provider-awscc_v1.12.0_x5 plugin crashed   | Using Datazone Module

### ISSUE THREAD

**Issue by ericpachecosousa** [hashicorp/terraform-provider-awscc#2057]
Hi team,

Regardless of the awscc version I'm using, I started encountering this issue today. It doesn't appear to be related to the version, as I have different codebases using various versions, and all are experiencing the same problem.

│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-awscc_v1.12.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb43872]

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-awscc/internal/generic.(*genericResource).Create(0xc001372d20, {0x33929c8?, 0xc003448990?}, {{{{0x3398cb0, 0xc00345dad0}, {0x21fe160, 0xc003456810}}, {0x33c9058, 0xc000529400}}, {{{0x3398cb0, ...}, ...}, ...}, ...}, ...)
	github.com/hashicorp/terraform-provider-awscc/internal/generic/resource.go:397 +0x792

**Comment by jar-b** [comment]
Relates #1480

`progressEvent` needs a nil check prior to referencing `Identifier`.

https://github.com/hashicorp/terraform-provider-awscc/blob/95b075ea8662912449ac202a587c3c7b521e5816/internal/generic/resource.go#L390-L397

**Comment by ericpachecosousa** [comment]
Hi guys like i said i tryed in different currency and i had the same problem as in bellow 

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-awscc_v1.15.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb4e0b2]

goroutine 163 [running]:
github.com/hashicorp/terraform-provider-awscc/internal/generic.(*genericResource).Create(0xc0014a15e0, {0x364fc28?, 0xc003848db0?}, {{{{0x3656050, 0xc003a59800}, {0x22dd5e0, 0xc003849e90}}, {0x3687078, 0xc000a07e00}}, {{{0x3656050, ...}, ...}, ...}, ...}, ...)
	github.com/hashicorp/terraform-provider-awscc/internal/generic/resource.go:397 +0x792
  # module.datazone[0].awscc_datazone_environment_blueprint_configuration.this["DefaultDataWarehouse"] will be created
  + resource "awscc_datazone_environment_blueprint_configuration" "this" {
      + created_at                       = (known after apply)
      + domain_id                        = (known after apply)
      + domain_identifier                = ""
      + enabled_regions                  = [
          + "sa-east-1",
          + "us-east-1",
        ]
      + environment_blueprint_id         = (known after apply)
      + environment_blueprint_identifier = "DefaultDataWarehouse"
      + id                               = (known after apply)
      + manage_access_role_arn           = "arn:aws:iam:::role/AmazonDataZoneRedshiftManageAccess-prd"
      + provisioning_role_arn            = "arn:aws:iam:::role/AmazonDataZoneDomainProvisioning-prd"
      + regional_parameters              = (known after apply)
      + updated_at                       = (known after apply)
    }

**Comment by ericpachecosousa** [comment]
Hi team, there is some deadline to fix this problem ?  I saw that there is a fix related, but i didn't see any new version

**Comment by jar-b** [comment]
Hi @ericpachecosousa - This will be included in the next release, currently scheduled for this Thursday, October 17.
