### ISSUE TITLE
 Add Quick Setup service setting for Explorer 

### ISSUE THREAD

**Issue by roshan-virtixhealth** [hashicorp/terraform-provider-awscc#2084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

Thanks for adding the "awscc_ssmquicksetup_configuration_manager" resource to provider. However i think one step that missing is also adding support to update Quick Setup service setting for Explorer. 

As  noted in this AWS doc: https://docs.aws.amazon.com/systems-manager/latest/userguide/quick-setup-getting-started.html#quick-setup-getting-started-iam (Step 4 under Manual Onboarding). 

### New or Affected Resource(s)

* awscc_ssmquicksetup_configuration_manager

### Potential Terraform Configuration

```hcl
resource "awscc_ssmquicksetup_service_setting" "ssm_service_setting" {
   setting_id    = "explorer-enabling-role-arn"
   setting_value = aws_iam_role.iam_role_ssm_patch_pol_explorer.arn
}
```

### References

* https://docs.aws.amazon.com/systems-manager/latest/userguide/quick-setup-getting-started.html#quick-setup-getting-started-iam (Step 4 under Manual Onboarding)
* https://github.com/hashicorp/terraform-provider-aws/pull/39633
Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation? For example:

* #0000

**Comment by quixoticmonk** [comment]
Thank you opening the issue @roshan-virtixhealth .  The AWSCC provider is autogenerated based on the services and features currently available with the CloudFormation registry. Your enhancement request looks like one for a new resource under the SSMQuickSetup which has to be available in CloudFormation registry for AWSCC to add to the support. 

It would be worth creating an [issue](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) on the CloudFormation roadmap repository for this.  Once this is available in CloudFormation, a Terraform resource will be generated under AWSCC in the release after.
