### ISSUE TITLE
awscc_s3_bucket failing in us-west-2

### ISSUE THREAD

**Issue by scottschreckengaust** [hashicorp/terraform-provider-awscc#2124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_s3_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = ">= 1.0.7"
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = ">= 1.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.6.0"
    }
  }
}

variable "region" {
  type    = string
  default = "us-west-2"
}

provider "awscc" {
  region = var.region
}

resource "random_string" "solution_prefix" {
  length  = 4
  special = false
  upper   = false
}

resource "awscc_s3_bucket" "s3_data_source" {
  bucket_name = "${random_string.solution_prefix.result}-sscce"

  public_access_block_configuration = {
    block_public_acls       = true
    block_public_policy     = true
    ignore_public_acls      = true
    restrict_public_buckets = true
  }

  bucket_encryption = {
    server_side_encryption_configuration = [{
      bucket_key_enabled = true
      server_side_encryption_by_default = {
        sse_algorithm     = "AES256"
        kms_master_key_id = null
      }
    }]
  }
}
```

### Debug Output

The below linked Gist is from:

```shell
% TF_LOG=json TF_LOG_CORE=TRACE TF_LOG_PROVIDER=TRACE TF_LOG_PATH=log.json terraform apply -auto-approve

...
Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID:
GUID, GeneralServiceException: AWS::S3::Bucket Handler returned status FAILED: The provided token is malformed or otherwise
invalid. (Service: S3, Status Code: 400, Request ID: TOKEN, Extended Request ID:
REQUESTID) (HandlerErrorCode: GeneralServiceException, RequestToken:
TOKEN)
```

https://gist.github.com/scottschreckengaust/3d0520805d8f36e2fc95daabd9de5d59

### Expected Behavior

```shell
% terraform apply
...
Plan: 2 to add, 0 to change, 0 to destroy.
random_string.solution_prefix: Creating...
random_string.solution_prefix: Creation complete after 0s [id=0r9l]
awscc_s3_bucket.s3_data_source: Creating...
awscc_s3_bucket.s3_data_source: Still creating... [10s elapsed]
awscc_s3_bucket.s3_data_source: Creation complete after 15s [id=0r9l-sscce]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

### Actual Behavior

```shell
% terraform apply
...
Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID:
GUID, GeneralServiceException: AWS::S3::Bucket Handler returned status FAILED: The provided token is malformed or otherwise
invalid. (Service: S3, Status Code: 400, Request ID: TOKEN, Extended Request ID:
REQUESTID) (HandlerErrorCode: GeneralServiceException, RequestToken:
TOKEN)

% terraform destroy
...
...
Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID:
GUID, GeneralServiceException: AWS::S3::Bucket Handler returned status FAILED: The provided token is malformed or otherwise
invalid. (Service: S3, Status Code: 400, Request ID: TOKEN, Extended Request ID:
REQUESTID) (HandlerErrorCode: GeneralServiceException, RequestToken:
TOKEN)
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy` # fails as above

The state is irrecoverable without removing the resource from the state:

1. `terraform state show wscc_s3_bucket.s3_data_source`
2. `aws s3 rb {s3://bucket-name-from-above}
3. `terraform state rm wscc_s3_bucket.s3_data_source`
4. `terraform destroy` #cleans up because the resource is gone...

### Important Factoids

- using `us-west-1`, `us-east-1` and `us-east-2` work as expected.
-  there is a successful resource request: 

```shell
% aws cloudcontrol list-resource-requests --region us-west-2
{
    "ResourceRequestStatusSummaries": [
...
        {
            "TypeName": "AWS::S3::Bucket",
            "Identifier": "XXXX-sscce",
            "RequestToken": "GUIDDIFFERENT",
            "Operation": "CREATE",
            "OperationStatus": "SUCCESS",
            "EventTime": "YYYY-MM-DDTHH:mm:ss.000000-00:00"
        },
...
```

### References

* #0000

**Comment by quixoticmonk** [comment]
Thank you for opening the issue @scottschreckengaust . I can reproduce it on us-west-2 and it feels like the re-conciliation of state after the create_complete is failing. The state file for the resource was null for most properties as the get call is failing here. 

```
aws cloudcontrol get-resource --type-name AWS::S3::Bucket --identifier 23kh-sscce
{
    "TypeName": "AWS::S3::Bucket",
    "ResourceDescription": {
        "Identifier": "23kh-sscce",
        "Properties": "{\"PublicAccessBlockConfiguration\":{\"RestrictPublicBuckets\":true,\"BlockPublicPolicy\":true,\"BlockPublicAcls\":true,\"IgnorePublicAcls\":true},\"BucketName\":\"23kh-sscce\",\"RegionalDomainName\":\"23kh-sscce.s3.us-west-2.amazonaws.com\",\"OwnershipControls\":{\"Rules\":[{\"ObjectOwnership\":\"BucketOwnerEnforced\"}]},\"DomainName\":\"23kh-sscce.s3.amazonaws.com\",\"BucketEncryption\":{\"ServerSideEncryptionConfiguration\":[{\"BucketKeyEnabled\":true,\"ServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]},\"WebsiteURL\":\"http://23kh-sscce.s3-website-us-west-2.amazonaws.com\",\"DualStackDomainName\":\"23kh-sscce.s3.dualstack.us-west-2.amazonaws.com\",\"Arn\":\"arn:aws:s3:::23kh-sscce\"}"
    }
}

```

```
aws cloudcontrol get-resource --type-name AWS::S3::Bucket --identifier 23kh-sscce --region us-west-2

An error occurred (GeneralServiceException) when calling the GetResource operation: AWS::S3::Bucket Handler returned status FAILED: The provided token is malformed or otherwise invalid. (Service: S3, Status Code: 400, Request ID: MS60GNCDS6T2192S, Extended Request ID: 42UPcPIAHzQkPQFD9uT9+rDt97bKPirJ/ZuayogaM0Z5OzGiVb8JkN1TfW3VWhbVPPnpdoTyHhk=) (HandlerErrorCode: GeneralServiceException, RequestToken: cb240cde-0251-447f-b6f6-a59ab2044930)

```

**Comment by scottschreckengaust** [comment]
This message repeats:

> ╷
>│ Error: Provider returned invalid result object after apply
> │
> │ After the apply operation, the provider still indicated an unknown value for FILLINWITHONEOFTHEBELOW. All values must be
> │ known after apply, so this is always a bug in the provider and should be reported in the provider's own repository. Terraform will still save the other
> │ known object values in the state.
> ╵

Here are the items:* awscc_s3_bucket.s3_data_source.accelerate_configuration
* awscc_s3_bucket.s3_data_source.access_control
* awscc_s3_bucket.s3_data_source.analytics_configurations
* awscc_s3_bucket.s3_data_source.arn
* awscc_s3_bucket.s3_data_source.bucket_encryption.server_side_encryption_configuration[0].server_side_encryption_by_default.kms_master_key_id. All values
* awscc_s3_bucket.s3_data_source.cors_configuration
* awscc_s3_bucket.s3_data_source.domain_name
* awscc_s3_bucket.s3_data_source.dual_stack_domain_name
* awscc_s3_bucket.s3_data_source.intelligent_tiering_configurations. All values
* awscc_s3_bucket.s3_data_source.inventory_configurations
* awscc_s3_bucket.s3_data_source.lifecycle_configuration
* awscc_s3_bucket.s3_data_source.logging_configuration
* awscc_s3_bucket.s3_data_source.metrics_configurations
* awscc_s3_bucket.s3_data_source.notification_configuration
* awscc_s3_bucket.s3_data_source.object_lock_configuration
* awscc_s3_bucket.s3_data_source.object_lock_enabled
* awscc_s3_bucket.s3_data_source.ownership_controls
* awscc_s3_bucket.s3_data_source.regional_domain_name
* awscc_s3_bucket.s3_data_source.replication_configuration
* awscc_s3_bucket.s3_data_source.tags
* awscc_s3_bucket.s3_data_source.versioning_configuration
* awscc_s3_bucket.s3_data_source.website_configuration
* awscc_s3_bucket.s3_data_source.website_url

**Comment by quixoticmonk** [comment]
@scottschreckengaust can you retest this ? I did see an update from the service team that the issues noticed across the regions should be resolved now. I did test with my examples which worked as expected.

**Comment by scottschreckengaust** [comment]
```shell
terraform apply -var="region=us-west-2" -auto-approve
...
random_string.solution_prefix: Creation complete after 0s [id=3qjz]
awscc_s3_bucket.s3_data_source: Creating...
awscc_s3_bucket.s3_data_source: Still creating... [10s elapsed]
awscc_s3_bucket.s3_data_source: Still creating... [20s elapsed]
awscc_s3_bucket.s3_data_source: Creation complete after 25s [id=3qjz-sscce]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

**Comment by quixoticmonk** [comment]
Closing the issue based on the retests. Please re-open if you see the issue on another region.
