### ISSUE TITLE
A better `AttributePlanModifier` for Computed,Optional,ForceNew attributes

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-awscc#222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the Cloudformation Open Coverage Roadmap.

Relates https://github.com/hashicorp/terraform-plugin-framework/issues/187.

A better (than `tfsdk.RequiresReplace()`) `AttributePlan` modifier for Computed, Optional, ForceNew attributes would be of the form:

```go
PlanModifiers: []tfsdk.AttributePlanModifier{
	tfsdk.RequiresReplaceIf(func(ctx context.Context, state, config attr.Value, path *tftypes.AttributePath) (bool, diag.Diagnostics) {
		if config.Equal(state) || config.Equal(types.String{Null: true}) {
			return false, nil
		}
		return true, nil
	}, "require replacement if configuration value changes", "require replacement if configuration value changes"),
},
```

with `config.Equal(types.String{Null: true})` replaced by the attribute's type.
Once https://github.com/hashicorp/terraform-plugin-framework/issues/193 is resolved this can be implemented generically.

**Comment by bflad** [comment]
> with config.Equal(types.String{Null: true}) replaced by the attribute's type.

Another option to keep it generic until https://github.com/hashicorp/terraform-plugin-framework/issues/193 is implemented would be to enumerate all the framework type cases, e.g.

```go
func ThisIsTheForceNewYouAreLookingFor() tfsdk.AttributePlanModifier {
	return tfsdk.RequiresReplaceIf(func(ctx context.Context, state, config attr.Value, path *tftypes.AttributePath) (bool, diag.Diagnostics) {
		if config.Equal(state) {
			return false, nil
		}

		// TODO: These can all be replaced with config.IsNull() when available
		// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/193

		if config.Equal(types.Bool{Null: true}) {
			return false, nil
		}

		if config.Equal(types.Float64{Null: true}) {
			return false, nil
		}

		if config.Equal(types.Int64{Null: true}) {
			return false, nil
		}

		if config.Equal(types.List{Null: true}) {
			return false, nil
		}

		if config.Equal(types.Map{Null: true}) {
			return false, nil
		}

		if config.Equal(types.Object{Null: true}) {
			return false, nil
		}

		if config.Equal(types.Number{Null: true}) {
			return false, nil
		}

		if config.Equal(types.Set{Null: true}) {
			return false, nil
		}

		if config.Equal(types.String{Null: true}) {
			return false, nil
		}

		return true, nil
}, "require replacement if configuration value changes", "require replacement if configuration value changes"),
}

```
