### ISSUE TITLE
awscc_backup_report_plan generates invalid plan

### ISSUE THREAD

**Issue by papile** [hashicorp/terraform-provider-awscc#324]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the Cloudformation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version
`Terraform v1.0.11
on linux_amd64`

### Affected Resource(s)

* awscc_backup_report_plan

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.1"
    }
  }
}

resource "aws_s3_bucket" "backup-reports" {
  bucket_prefix = "backup-reports"
}


resource "awscc_backup_report_plan" "backup-report" {
  report_plan_name = "backup1JobReport"
  report_delivery_channel = {
    s3_bucket_name = aws_s3_bucket.backup-reports.bucket
    s3_key_prefix = "backup-reports"
    formats = ["CSV", "JSON"]
  }
  report_setting = {
    report_template = "BACKUP_JOB_REPORT"
    framework_arns = []
  }
}
```

### Expected Behavior

Terraform should have refreshed the state and generated a valid plan

### Actual Behavior
It works on the initial apply but subsequent state refresh and plan/apply generate the following error
```
│ Provider "registry.terraform.io/hashicorp/awscc" planned an invalid value for
│ awscc_backup_report_plan.backup-report.report_plan_tags: planned value
│ cty.ListValEmpty(cty.Object(map[string]cty.Type{"key":cty.String, "value":cty.String})) for a
│ non-computed attribute.
```

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

**Comment by dylanmtaylor** [comment]
We are also hitting this in our environment. Apply worked just fined but on planning after doing an apply, we hit this issue.

**Comment by dylanmtaylor** [comment]
We found a workaround for our setup for this. Might help you:
* Create a random tag - "name": "value" or something in AWS.
* Add a tag in TF -- example:

```
esource "awscc_backup_report_plan" "backup-report" {
  report_plan_name = "backup_jobs_report"
  report_delivery_channel = {
    s3_bucket_name = aws_s3_bucket.backup_reports.bucket
    s3_key_prefix = "backup-reports"
    formats = ["CSV", "JSON"]
  }
  report_setting = {
    report_template = "BACKUP_JOB_REPORT"
    framework_arns = []
  }
  report_plan_tags = [ 
    {
      key =  "Environment",
      value = "${var.environment_tag}"
    }
  ]
}
```

* Apply TF. This should fix the issue.
