### ISSUE TITLE
awscc_iot_domain_configuration: apply fails

### ISSUE THREAD

**Issue by dewbacks** [hashicorp/terraform-provider-awscc#330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

```
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.69.0
+ provider registry.terraform.io/hashicorp/awscc v0.9.0
```

### Affected Resource(s)

* awscc_iot_domain_configuration

### Terraform Configuration Files

```hcl
module "mqtt_acm" {
  source  = "terraform-aws-modules/acm/aws"
  version = "~> v3.0"

  domain_name = local.mqtt_custom_endpoint_name
  zone_id     = data.aws_route53_zone.external_region_zone.zone_id
}

resource "awscc_iot_domain_configuration" "this" {
  domain_configuration_name = "device_mqtt"
  domain_configuration_status = "ENABLED"
  domain_name = local.mqtt_custom_endpoint_name
  service_type = "DATA"
  server_certificate_arns = [module.mqtt_acm.acm_certificate_arn]
}
```

### Expected Behavior

TF apply succeeds.

### Actual Behavior

The IoT domain configuration does get created (quickly) within AWS, however the terraform apply waits for 40 seconds and returns error.

```
module.mqtt.awscc_iot_domain_configuration.this: Creating...
module.mqtt.awscc_iot_domain_configuration.this: Still creating... [10s elapsed]
module.mqtt.awscc_iot_domain_configuration.this: Still creating... [20s elapsed]
module.mqtt.awscc_iot_domain_configuration.this: Still creating... [30s elapsed]
module.mqtt.awscc_iot_domain_configuration.this: Still creating... [40s elapsed]
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for module.mqtt.awscc_iot_domain_configuration.this.server_certificates. All values must be known after apply, so this is always a bug in the provider and should be reported in the provider's own repository.
│ Terraform will still save the other known object values in the state.
╵
╷
│ Error: Creation Of Terraform State Unsuccessful
│ 
│   with module.mqtt.awscc_iot_domain_configuration.this,
│   on ../../../../modules/services/mqtt/endpoint.tf line 67, in resource "awscc_iot_domain_configuration" "this":
│   67: resource "awscc_iot_domain_configuration" "this" {
│ 
│ Unable to set Terraform State Unknown values from Cloud Control API Properties. This is typically an error with the Terraform provider implementation. Original Error: error setting value at AttributeName("server_certificates"): 1 error occurred:
│ 	* An unexpected error was encountered trying to convert from value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ cannot use type map[string]interface {} as schema type types.ObjectType; types.ObjectType must be an attr.TypeWithElementType to hold map[string]interface {}

```

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
Similar: #266.
