### ISSUE TITLE
awscc_ses_contact_list plan fails

### ISSUE THREAD

**Issue by cbelsole** [hashicorp/terraform-provider-awscc#339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

```
$ tf --version
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/awscc v0.9.0
```

### Affected Resource(s)

* awscc_ses_contact_list

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "awscc_ses_contact_list" "weekly_Subscription" {
  contact_list_name = "Some name"
  description       = "Some description"
  topics = [
    {
      topic_name                  = "WeeklyEvents"
      display_name                = "Weekly Events"
      description                 = "Some description"
      default_subscription_status = "OPT_IN"
    }
  ]
}
```

### Debug Output

```
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/hashicorp/awscc" planned an invalid value for awscc_ses_contact_list.weekly_Subscription.tags: planned value
│ cty.ListValEmpty(cty.Object(map[string]cty.Type{"key":cty.String, "value":cty.String})) for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Panic Output

N/A

### Expected Behavior

Terraform should generate a valid plan.

### Actual Behavior

Terraform failed with the above error due to an invalid plan.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This worked initially and created the resource. I was working on a dynamoDB resource and tried to generate another plan when this error came up. Removing the dynamoDB resource does not resolve the issue.

### References

* N/A

**Comment by cbelsole** [comment]
Stubbing out the tags on the contact list with:
```
  tags = [
    {
      key   = "test"
      value = "test"
    }
  ]
```

seems to get me past the planning error.

**Comment by ewbankkit** [comment]
Verified that this error no longer occurs:

```console
% terraform apply
...
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # awscc_mediapackage_channel.this will be created
  + resource "awscc_mediapackage_channel" "this" {
      + arn         = (known after apply)
      + description = "Managed by Terraform."
      + hls_ingest  = {
        + ingest_endpoints = [
            + {            },
          ] -> (known after apply)
      }
      + id          = "some-id"
      + tags        = [
          + {          },
        ] -> (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

awscc_mediapackage_channel.this: Creating...
awscc_mediapackage_channel.this: Creation complete after 6s [id=some-id]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
