### ISSUE TITLE
memorydb append user to ACL

### ISSUE THREAD

**Issue by adamstrawson** [hashicorp/terraform-provider-awscc#341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

When creating MemoryDB Users, you create the ACL as part of the cluster creation. There is then no way to add a user later on via Terraform. 

We have a module that handles cluster creation, and another module that handles user creation for services. If you later try to create a new user independently, it's not possible to append to an existing ACL. 

Attempting to create a user, and attach to an ACL results in `AlreadyExists` error.

### New or Affected Resource(s)

* awscc_memorydb_acl
* awscc_memorydb_user

### Potential Terraform Configuration

```hcl
# This ACL already exists and was created at cluster creation for `awscc_memorydb_cluster` as 
# `acl_name` is a required field.
resource "awscc_memorydb_acl" "aws_memorydb_acl" {
  acl_name   = "my-acl"
  user_names = [awscc_memorydb_user.aws_memorydb_user.user_name]
}

resource "awscc_memorydb_user" "aws_memorydb_user" {
  access_string = "on ~* &* +@all"
  authentication_mode = {
    passwords = ["foobar"]
    type      = "password"
  }
  user_name = "helloworld"
}
```

**Comment by gdavison** [comment]
Hi @adamstrawson, thanks for raising this. Because of how the AWS API for MemoryDB works, the list of users gets passed to the ACL at either creation or update time.

If you are creating the users in a separate module, the list of usernames will have to be output from the user module and passed as an input to the module that creates the MemoryDB.
