### ISSUE TITLE
Specifying no tags yields error on 2nd `apply`

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-awscc#342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_ec2_vpc

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.9"
    }
  }
}

# Configure the AWS Cloud Control Provider
provider "awscc" {
  region = "us-east-1"
}

resource "awscc_ec2_vpc" "test" {
    cidr_block = "10.0.0.0/16"
}
```

### Expected Behavior

should refresh

### Actual Behavior

on 2nd `apply` we get an error:

```
$ tf apply
awscc_ec2_vpc.test: Refreshing state... [id=vpc-<>]
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hashicorp/awscc" planned an invalid value for awscc_ec2_vpc.test.tags: planned value
│ cty.ListValEmpty(cty.Object(map[string]cty.Type{"key":cty.String, "value":cty.String})) for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

1. `terraform apply`
1. `terraform apply`

### References

* #0000

**Comment by gdavison** [comment]
Investigation notes: The `DEBUG` log includes the following during a `plan` after the first `apply`:

```
2022-01-18T18:01:48.152-0800 [WARN]  Provider "registry.terraform.io/hashicorp/awscc" produced an unexpected new value for awscc_ec2_vpc.test during refresh.
      - .enable_dns_hostnames: was null, but now cty.False
      - .enable_dns_support: was null, but now cty.True
      - .instance_tenancy: was null, but now cty.StringVal("default")
      - .tags: was null, but now cty.ListValEmpty(cty.Object(map[string]cty.Type{"key":cty.String, "value":cty.String}))
```

Because of the failure in `plan` the resources cannot be destroyed using `terraform destroy`
