### ISSUE TITLE
Some resources missing tags parameter

### ISSUE THREAD

**Issue by bcatubig** [hashicorp/terraform-provider-awscc#356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

`tag` parameter missing from some resources. Is it possible to add this parameter in? Or is it based on the awscc schemas?

### New or Affected Resource(s)

For my use case,

* awscc_awscc_location_place_index

### Potential Terraform Configuration

```hcl
resource "awscc_location_place_index" "this" {
  data_source               = var.data_source
  index_name                = var.index_name
  pricing_plan              = var.pricing_plan
  data_source_configuration = var.data_source_configuration
  description               = var.description
  tags                      = {} # standard tag map(string)
}
```

**Comment by gdavison** [comment]
Hi @bcatubig. The provider is generated using the Cloud Formation resources exposed by Cloud Control. Unfortunately, the Cloud Formation equivalent for `awscc_location_place_index`, [`AWS::Location::PlaceIndex`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-location-placeindex.html) does not define a tags field.
