### ISSUE TITLE
[awscc_s3_bucket] cannot use object_lock_configuration

### ISSUE THREAD

**Issue by thebigcosinus** [hashicorp/terraform-provider-awscc#366]
Hi,

First time with this new provider, I tried to create an s3 bucket with object lock configuration.

I always get the following error "Object Lock configuration cannot be enabled on existing buckets", even if this is a new bucket created by the same Terraform Plan

```terraform
resource "awscc_s3_bucket" "storage_bucket" {
  bucket_name = var.storage_bucket_name
  object_lock_configuration = {
    object_lock_enabled = "Enabled"
  }
}
```

**Comment by gdavison** [comment]
Hi @thebigcosinus, to clarify, when you say

> even if this is a new bucket created by the same Terraform Plan

do you mean that you're defining the S3 bucket and then later enabling the object lock? Something like

```terraform
resource "awscc_s3_bucket" "storage_bucket" {
  bucket_name = var.storage_bucket_name
}

...

# And then later
resource "awscc_s3_bucket" "storage_bucket" {
  bucket_name = var.storage_bucket_name
  object_lock_configuration = {
    object_lock_enabled = "Enabled"
  }
}
```

If so, you can only define a Terraform resource once in a Terraform configuration. You cannot redefine settings at a later time.

If I have misunderstood, can you include the relevant parts of your Terraform configuration and the debug log, please? To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).

**Comment by thebigcosinus** [comment]
Hi,

My Terraform is 



terraform {
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = "0.10.0"
    }
  }
}


provider "awscc" {
  region = "us-east-1"
}

resource "awscc_s3_bucket" "storage_bucket" {
  bucket_name = "mytestbucketthebigcosinus"
  object_lock_configuration = {
    object_lock_enabled = "Enabled"
  }
}
`
`
 And I ve the following message
`
│ Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED. StatusMessage: Object Lock configuration cannot be enabled on
│ existing buckets (Service: S3, Status Code: 409, Request ID: PRTBXN8K7XEHNKY3, Extended Request ID: lFH0+o99iyW1+wY32tGfAL6Vj/TfTF86tg6oI4r435+mWXN6Le/A4fFf+glzxgzIuMnSEVhMELQ=). ErrorCode:
│ GeneralServiceException`

**Comment by gdavison** [comment]
Ah, sorry, I misunderstood. I have reproduced this error.

This looks like an error in the underlying Cloud Formation resource. There is an open issue for this at https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1040

**Comment by drewmullen** [comment]
resolved upstream
