### ISSUE TITLE
awscc_cloudfront_distribution: Desired state does not match remote state after apply

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-awscc#389]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_cloudfront_distrubtion

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
TBC
```

### Expected Behavior

Desired state does not match remote state after apply

### Actual Behavior

Desired state matches remote state after apply

### Steps to Reproduce

```console
terraform apply

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.

terraform plan

  # module.foo.awscc_cloudfront_distribution.main will be updated in-place
  ~ resource "awscc_cloudfront_distribution" "main" {
      ~ distribution_config = {
          ~ default_cache_behavior = {
              + default_ttl                = (known after apply)
              + max_ttl                    = (known after apply)
              + min_ttl                    = (known after apply)
              + origin_request_policy_id   = (known after apply)
              + realtime_log_config_arn    = (known after apply)
              + response_headers_policy_id = (known after apply)
                # (7 unchanged attributes hidden)
            }
          - logging                = {
              - include_cookies = false -> null
            }
          ~ viewer_certificate     = {
              - cloudfront_default_certificate = false -> null
                # (3 unchanged attributes hidden)
            }
            # (10 unchanged attributes hidden)
        }
        id                  = "BBBBIKIDBBBBB
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

### Important Factoids

CC API may not return all values
- viewer_certificate.cloudfront_default_certificate
- logging.include_cookies

**Comment by ewbankkit** [comment]
@breathingdust Do you have the Terraform configuration that triggers this.
