### ISSUE TITLE
Modules that define a provider configuration cause errors if removed from tf configuration calling the module

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-awscc#466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* all resources

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```bash
$ cat main.tf

module "name" {
  source = "./module"
}
```

`$ cat module/main.tf`

```hcl
resource "awscc_ec2_vpc" "name" {
  for_each = toset(["10.0.0.0/16"])
  cidr_block = each.key
  enable_dns_hostnames = false
  enable_dns_support = true
  instance_tenancy = "default"
}


provider "awscc" {
  user_agent = [{
    product_name    = "terraform-awscc-vpc"
    product_version = "0.0.1"
    comment         = "test"
  }]
}
```
1. Perform a terraform apply
1. Once complete, comment out `main.tf` module declaration
1. Run terraform apply again

```
│ Error: Provider configuration not present
│ 
│ To work with module.name.awscc_ec2_vpc.name["10.0.0.0/16"] (orphan) its original provider configuration at
│ module.name.provider["registry.terraform.io/hashicorp/awscc"] is required, but it has been removed. This occurs when a
│ provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider
│ configuration to destroy module.name.awscc_ec2_vpc.name["10.0.0.0/16"] (orphan), after which you can remove the provider
│ configuration again.
```

### Expected Behavior

should delete the module resourcs

### Actual Behavior

error (see above) 

### Steps to Reproduce

see above

**Comment by drewmullen** [comment]
Currently theres a work around of `terraform destroy -target module.name`

**Comment by drewmullen** [comment]
Upon further research, in all circumstances it seems that [providers should not be declared in modules](https://github.com/hashicorp/terraform/issues/30628). We were attempting to use a provider block to merely define an [extra user-agent](https://github.com/aws-ia/terraform-aws-vpc/blob/5718fc1d63b64e104807e41bf318cb820020bae9/providers.tf#L16). we're going to revert that change and look at using the [ProviderMeta](https://www.terraform.io/internals/provider-meta) feature instead.

**Comment by ryanpeach** [comment]
> Upon further research, in all circumstances it seems that [providers should not be declared in modules](https://github.com/hashicorp/terraform/issues/30628). We were attempting to use a provider block to merely define an [extra user-agent](https://github.com/aws-ia/terraform-aws-vpc/blob/5718fc1d63b64e104807e41bf318cb820020bae9/providers.tf#L16). we're going to revert that change and look at using the [ProviderMeta](https://www.terraform.io/internals/provider-meta) feature instead.

Is this really the correct way to do things? For example we have a helm provider and an eks module with some helm addons. If we define the helm provider at some root which uses the eks module, but we define the helm provider at that root, we have to use outputs of the eks module to define the provider, which causes a dependency issue. As such, the helm provider is best put in the module.
