### ISSUE TITLE
awscc - sts token expiry - stuck in "Still Creating"

### ISSUE THREAD

**Issue by troyparrett** [hashicorp/terraform-provider-awscc#486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/awscc v0.19.0

### Affected Resource(s)

awscc_kendra_index
possibly others

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.1"
    }
  }
}

# Configure the AWS Provider
provider "awscc" {
  region = "us-east-1"
}

resource "awscc_kendra_index" "demo1" {
  edition  = "ENTERPRISE_EDITION"
  name     = "my-test-demo1"
  role_arn = "arn:aws:iam::<redacted>:role/service-role/AmazonKendra-us-east-1-test"

}
```

### Debug Output
2022-05-04T18:59:22.588Z [DEBUG] provider.terraform-provider-awscc: [aws-sdk-go-v2]: tf_req_id=... tf_resource_type=awscc_kendra_index tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-provider-awscc/internal/provider/provider.go:449 @module=awscc cfn_type=AWS::Kendra::Index message="Response
HTTP/1.1 400 Bad Request^M
Content-Length: 125^M
Content-Type: application/x-amz-json-1.0^M
Date: Wed, 04 May 2022 18:59:22 GMT^M

{"__type":"com.amazon.coral.service#ExpiredTokenException","message":"The security token included in the request is expired"}" tf_provider_addr=hashicorp/awscc timestamp=2022-05-04T18:59:22.588Z

### Expected Behavior
I would expect some sort of error handling.

### Actual Behavior

Appear to be stuck in a loop outputting this:
Still creating... [50m50s elapsed]

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running from AWS Cloud9

* #0000

**Comment by ewbankkit** [comment]
Similar (in `terraform-provider-aws`):

* https://github.com/hashicorp/terraform-provider-aws/issues/4502
* https://github.com/hashicorp/terraform-provider-aws/issues/1351
* https://github.com/hashicorp/terraform-provider-aws/issues/12023

**Comment by ewbankkit** [comment]
This

https://github.com/hashicorp/terraform-provider-awscc/blob/c866efe4a567ace59dfcdfd7228a030e4d733cdf/internal/service/cloudcontrol/waiter.go#L14-L36

may be the culprit, suppressing any `error`.
I'll investigate further.
