### ISSUE TITLE
awscc rds cluster creation error

### ISSUE THREAD

**Issue by snehal1219901** [hashicorp/terraform-provider-awscc#515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

AWSCC_Provider % terraform -v
Terraform v1.1.7
on darwin_amd64

### Affected Resource(s)

* awscc_rds_global_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

provider "awscc" {
  region = "us-east-1"

}

resource "awscc_rds_global_cluster" "rdsdb" {
  id = "test"
  engine = "aurora"
}

### Expected Behavior

Should create rds cluster

### Actual Behavior

╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hashicorp/awscc" planned an invalid value for awscc_rds_global_cluster.rdsdb.id: planned value
│ cty.NullVal(cty.String) does not match config value cty.StringVal("test").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

terraform init
terraform plan

**Comment by ewbankkit** [comment]
@snehal1219901 Thanks for raising this issue 👏.
With the sample configuration I get an error:

```console
% terraform plan
...
Error: Invalid Configuration for Read-Only Attribute
│ 
│   with awscc_rds_global_cluster.rdsdb,
│   on main.tf line 6, in resource "awscc_rds_global_cluster" "rdsdb":
│    6:   id     = "test"
│ 
│ Cannot set value for this attribute as the provider has marked it as read-only. Remove the configuration line setting the
│ value.
│ 
│ Refer to the provider documentation or contact the provider developers for additional information about configurable and
│ read-only attributes that are supported.
```

The `id` attribute is set by the provider after resource creation and cannot be specified in configuration.
You can use the `global_cluster_identifier` argument to configured a cluster identifier (or omit it if you specify `engine`):

```console
% terraform apply
...
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # awscc_rds_global_cluster.rdsdb will be created
  + resource "awscc_rds_global_cluster" "rdsdb" {
      + engine                       = "aurora"
      + engine_version               = (known after apply)
      + global_cluster_identifier    = (known after apply)
      + id                           = (known after apply)
      + source_db_cluster_identifier = (known after apply)
      + storage_encrypted            = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

awscc_rds_global_cluster.rdsdb: Creating...
awscc_rds_global_cluster.rdsdb: Creation complete after 6s [id=tbkimwhnwzzwoies1lpiptof5-svktrzlecokp]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
