### ISSUE TITLE
Support for iam_policy_attachment, iam_role_policy_attachment, iam_user_policy_attachment, iam_group_policy_attachment

### ISSUE THREAD

**Issue by maheshr-amzn** [hashicorp/terraform-provider-awscc#517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

As of Hashicorp Terraform awscc provider version 0.22.0, iam_policy_attachment, iam_role_policy_attachment, iam_user_policy_attachment, iam_group_policy_attachment are not supported.
This feature is nice to have to attach policies to new or existing IAM roles/users/groups.

### New or Affected Resource(s)

* awscc_0.22.0

### References
https://github.com/hashicorp/terraform-provider-awscc/issues/516

**Comment by breathingdust** [comment]
Hi @maheshr-amzn 👋 This is a generated provider, meaning that the resources are made available as they are added to the CloudFormation registry. If you see something missing please let the AWS team know in the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap)

**Comment by maheshr-amzn** [comment]
Thanks @breathingdust for you reply. I understand that as per the AWS resources are made available in Cloudformation registry. However, if you see the below snapshot, support for IAM policy attachments have been there for a long time.
![image](https://user-images.githubusercontent.com/80021638/190972219-69c7c308-053a-48cd-ba1e-14a386a3e1c3.png)
This feature is there in terraform AWS provider, but it's missing in terraform AWSCC provider as you can see from these links:
[IAM Policy Attachment TF AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy_attachment)
[IAM Role Policy Attachment TF AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy_attachment)
[IAM User Policy Attachment TF AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy_attachment)
[IAM Group Policy Attachment TF AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_group_policy_attachment)

Could you please confirm if awscc provider also depends on this public Cloudformation registry or is there some other registry of cloudformation specific to CloudControl API? It would be great if you can point us to the correct direction in this case.
