### ISSUE TITLE
Support for security_group, security_group_rule

### ISSUE THREAD

**Issue by maheshr-amzn** [hashicorp/terraform-provider-awscc#520]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

As of Hashicorp Terraform awscc provider version 0.22.0, security_group, security_group_rule are not supported.

### New or Affected Resource(s)

* awscc_0.22.0

**Comment by breathingdust** [comment]
Hi @maheshr-amzn 👋 This is a generated provider, meaning that the resources are made available as they are added to the CloudFormation registry. If you see something missing please let the AWS team know in the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap)

**Comment by maheshr-amzn** [comment]
Thanks @breathingdust for you reply. I understand that as per the AWS resources are made available in Cloudformation registry. However, if you see the below snapshot, support for security group and security group Ingress and Egress rules have been there for a long time. This feature is there in terraform AWS provider, but it's missing in terraform AWSCC provider.
![image](https://user-images.githubusercontent.com/80021638/190970196-cda876b3-bbc6-4166-a073-7a0aee9ef639.png)
![image](https://user-images.githubusercontent.com/80021638/190970408-604fe47b-b0af-4b22-8a76-01d1b87e29e6.png)
![image](https://user-images.githubusercontent.com/80021638/190970519-71b88f59-ea51-4707-8515-6109d9bc1694.png)

Could you please confirm if awscc provider also depends on this public Cloudformation registry or is there some other registry of cloudformation specific to CloudControl API? It would be great if you can point us to the correct direction in this case.
