### ISSUE TITLE
Support for awscc_eks_cluster_auth

### ISSUE THREAD

**Issue by maheshr-amzn** [hashicorp/terraform-provider-awscc#522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

As of Hashicorp Terraform awscc provider version 0.22.0, awscc_eks_cluster_auth is not supported.
This feature is for getting an authentication token to communicate with an EKS cluster.
This Uses IAM credentials from the AWS provider to generate a temporary token that is compatible with [AWS IAM Authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) authentication. This can be used to authenticate to an EKS cluster or to a cluster that has the AWS IAM Authenticator server configured.

### New or Affected Resource(s)

* awscc_0.22.0

### References
https://github.com/kubernetes-sigs/aws-iam-authenticator

**Comment by breathingdust** [comment]
Hi @maheshr-amzn 👋 This is a generated provider, meaning that the resources are made available as they are added to the CloudFormation registry. If you see something missing please let the AWS team know in the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap)
