### ISSUE TITLE
awscc_networkmanager_core_network tries to update owner_account attribute in-place and hangs

### ISSUE THREAD

**Issue by sundar-shanmugam** [hashicorp/terraform-provider-awscc#560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Affected Resource(s)

* awscc_networkmanager_core_network

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
resource "awscc_networkmanager_core_network" "core_network" {
  description       = "Sample Core Network"
  global_network_id = awscc_networkmanager_global_network.global_network.id
  policy_document   = data.aws_networkmanager_core_network_policy_document.core_nw_policy.json
}
```

### Debug Output
```
# module.test.awscc_networkmanager_core_network.core_network will be updated in-place
  ~ resource "awscc_networkmanager_core_network" "core_network" {
        id                = "core-network-xxxx"
      + owner_account     = (known after apply)
        # (9 unchanged attributes hidden)
```

### Panic Output

The in-place update just runs for more than an hour with no success, though it shouldn’t try to do that first place.

### Expected Behavior

1) Core Network gets created successfully
2) If there are no changes to the resource, the subsequent plan should not show any in-place updates on any attribute

### Actual Behavior

1) Core Network gets created successfully
2) Making no changes, if I do a terraform plan/apply, it tries to perform in-place update on owner_account attribute and just hangs for more than an hour (doesn't complete either)

### Steps to Reproduce

1. `terraform apply`
```
resource "awscc_networkmanager_global_network" "global_network" {
  #Deploy Global Network
  description = "Sample Global Network"
  tags = [{
    key   = "Name"
    value = "global-network-sample"
  }]
}

resource "awscc_networkmanager_core_network" "core_network" {
  #Deploy Core Network
  description       = "Sample Core Network"
  global_network_id = awscc_networkmanager_global_network.global_network.id
  policy_document   = data.aws_networkmanager_core_network_policy_document.core_nw_policy.json
}

data "aws_networkmanager_core_network_policy_document" "core_nw_policy" {
  core_network_configuration {
    vpn_ecmp_support = false
    asn_ranges       = ["64512-64555"]
    edge_locations {
      location = "us-east-1"
      asn      = 64512
    }
    edge_locations {
      location = "eu-central-1"
      asn      = 64513
    }
  }

  segments {
    name                          = "shared"
    description                   = "Segment for shared services"
    require_attachment_acceptance = true
  }
  segments {
    name                          = "prod"
    description                   = "Segment for prod services"
    require_attachment_acceptance = true
  }

  segment_actions {
    action     = "share"
    mode       = "attachment-route"
    segment    = "shared"
    share_with = ["*"]
  }

  attachment_policies {
    rule_number     = 100
    condition_logic = "or"

    conditions {
      type     = "tag-value"
      operator = "equals"
      key      = "segment"
      value    = "shared"
    }
    action {
      association_method = "constant"
      segment            = "shared"
    }
  }
  attachment_policies {
    rule_number     = 200
    condition_logic = "or"

    conditions {
      type     = "tag-value"
      operator = "equals"
      key      = "segment"
      value    = "prod"
    }
    action {
      association_method = "constant"
      segment            = "prod"
    }
  }
}
```

**Comment by drewmullen** [comment]
This is resolved if you wrap the `policy_document` in `jsonencode(jsondecode())` which is currently known as a required workaround while we wait for a feature from the terraform plugin framework

```terraform
resource "awscc_networkmanager_core_network" "core_network" {
  #Deploy Core Network
  description       = "Sample Core Network"
  global_network_id = awscc_networkmanager_global_network.global_network.id
  policy_document   = jsonencode(jsondecode(data.aws_networkmanager_core_network_policy_document.core_nw_policy.json))
}
```

**Comment by drewmullen** [comment]
@ewbankkit it is strange though that `owner_account` does not get added to statefile and causes a recreate if you omit the json encoder. not sure if its worth investigating before https://github.com/hashicorp/terraform-plugin-framework/pull/178 or if removing the override code will solve /shrug


`$ terraform state show awscc_networkmanager_core_network.core_network | grep "owner_account"` -> nothing

**Comment by ewbankkit** [comment]
As `owner_account_id` is `Computed`-only:

https://github.com/hashicorp/terraform-provider-awscc/blob/74921a168a2cf527e1e96b381497762adb92ff6e/internal/aws/networkmanager/core_network_resource_gen.go#L150-L163

Terraform will report in the plan that it will return a value that is only known after `apply`.
As Drew mentions, Terraform is saying that there is a plan as the missing `jsonencode(jsondecode(...))` causes a difference in the policy document.
