### ISSUE TITLE
Unable to create Network Manager core network

### ISSUE THREAD

**Issue by gagan-eg** [hashicorp/terraform-provider-awscc#583]
Can someone help. I might be doing something wrong possibly but I haven't found anything related to this error other places.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
+ provider registry.terraform.io/hashicorp/awscc v0.27.0

Your version of Terraform is out of date! The latest version
is 1.2.5. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

awscc_networkmanager_core_network

* awscc_XXXXX

### Terraform Configuration Files

awscc_networkmanager_core_network.gateway_core_network: Creating...
╷
│ Error: AWS SDK Go Service Operation Unsuccessful
│ 
│   with awscc_networkmanager_core_network.gateway_core_network,
│   on global_network.tf line 15, in resource "awscc_networkmanager_core_network" "gateway_core_network":
│   15: resource "awscc_networkmanager_core_network" "gateway_core_network" {
│ 
│ Calling Cloud Control API service CreateResource operation returned: operation error CloudControl: CreateResource, https response error StatusCode: 400, RequestID:
│ fc3d7b21-5270-4761-ba5c-3f5003620eaa, TypeNotFoundException: The type 'AWS::NetworkManager::CoreNetwork' cannot be found.
╵

```hcl
resource "awscc_networkmanager_core_network" "gateway_core_network" {
  description       = "Gateway Core Network"
  global_network_id = awscc_networkmanager_global_network.gateway_network.id
  # Compose jsonencode and jsondecode to produce a normalized JSON string.
  policy_document = jsonencode(jsondecode(data.aws_networkmanager_core_network_policy_document.gateway_network_policy_document.json))
  tags            = [
        {
            key   = "Name"
            value = format("%s-core-%s", var.env_prefix, var.network_suffix)
        },
        {
            key = "Environment"
            value = var.env_prefix
        }
    ]
}
```

### Debug Output

None

### Panic Output

awscc_networkmanager_core_network.gateway_core_network: Creating...
╷
│ Error: AWS SDK Go Service Operation Unsuccessful
│ 
│   with awscc_networkmanager_core_network.gateway_core_network,
│   on global_network.tf line 15, in resource "awscc_networkmanager_core_network" "gateway_core_network":
│   15: resource "awscc_networkmanager_core_network" "gateway_core_network" {
│ 
│ Calling Cloud Control API service CreateResource operation returned: operation error CloudControl: CreateResource, https response error StatusCode: 400, RequestID:
│ fc3d7b21-5270-4761-ba5c-3f5003620eaa, TypeNotFoundException: The type 'AWS::NetworkManager::CoreNetwork' cannot be found.

### Expected Behavior
Should be able to create core network

### Actual Behavior

Type error from Go SDK

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* #0000

**Comment by ewbankkit** [comment]
@gagan-eg Thanks for raising this issue.
Which AWS Region are you running Terraform in?

**Comment by gagan-eg** [comment]
I am running it in us-west-2. I have created a core network by hand and tested everything already so it does work in that region.

**Comment by gagan-eg** [comment]
@ewbankkit is this an issue with the specific region or am I doing something wrong? Thanks

**Comment by bayazee** [comment]
@gagan-eg check your CloudTrail logs. I had same issue and after checking the logs I saw this message:

`Global Network ID is already associated with another core network.`

If that is the case maybe try importing it.

**Comment by ewbankkit** [comment]
`TypeNotFoundException` usually means that the underlying CloudFormation resource type as mentioned in the error (here `AWS::NetworkManager::CoreNetwork`) is not supported in the target AWS Region.
We generate the provider resource schemas from the CloudFormation resource types supported in `us-east-1` (assumption is that this is the superset of all possible resource types) and so there may be cases where a resource type is not (yet) supported in another AWS Region.
However I am able to create core networks in `us-west-2`.
@gagan-eg Are you still getting the error?
