### ISSUE TITLE
awscc_msk_batch_scram_secret overrides/removes existing secret associations

### ISSUE THREAD

**Issue by mtranter** [hashicorp/terraform-provider-awscc#631]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/awscc v0.29.0

### Affected Resource(s)

* awscc_msk_batch_scram_secret

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "awscc_msk_batch_scram_secret" "assoc" {
  cluster_arn     = data.aws_msk_cluster.cluster.arn
  secret_arn_list = [aws_secretsmanager_secret.secret.arn]
}
```

### Expected Behavior

A new secret should be associated - along with existing secrets - in MSK 

### Actual Behavior

Existing resources that are not defined in this terraform stack (or in another stack) should not be removed.
This is needed to avoid a centralized management of secrets associated to a MSK cluster.

### Steps to Reproduce

1. Create a MSK cluster with some secrets associated on it in a first terraform stack
2. Create another terraform stack that associate new secrets to new previously created MSK cluster
3. terraform apply
4. terraform plan

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/16791

**Comment by ewbankkit** [comment]
This is the functionality of the underlying [`AWS::MSK::BatchScramSecret`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-batchscramsecret.html) CloudFormation resource type.
