### ISSUE TITLE
Cannot import awscc_quicksight_data_set

### ISSUE THREAD

**Issue by ioannis-klonatos** [hashicorp/terraform-provider-awscc#688]
### Affected Resource(s)

awscc_quicksight_data_set

### Description

I am not entirely sure this is a bug, but the documentation does not exactly specify the expected format of resource ID for QuickSight datasets. I tried increasing log level, but there is nothing more being printed in the output (GetResource fails with the error message below). I am using SSO to authenticate to the account, and the inferred account id seems to be correct. I found this: https://github.com/hashicorp/terraform-provider-awscc/issues/125 while looking for a solution but I am not sure if it is related. 

### Output 
```
│ Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error
│ StatusCode: 400, RequestID: cd7c7ac8-6da9-49fe-b485-206bea71c2ef, api error ValidationException: Identifier
│ 8a5dcfc0-25d1-4490-8cb0-91aa5b87cf63 is not valid for identifier [/properties/AwsAccountId, /properties/DataSetId]
```
### Expected Behavior

The object should have been imported

### Actual Behavior

Invalid identifier error thrown.

### Steps to Reproduce

Trying to import a pre-existing Quicksight dataset fails with unknown identifier

**Comment by breathingdust** [comment]
It looks like importing this requires a composite key, but at present we are not generating adequate guidance when that type of key is specified. It looks like the correct format would be "`AwsAccountId,DataSetId`".

https://github.com/hashicorp/terraform-provider-awscc/blob/c5f88170f21cad8e2b91ec4a5f1ac70b60d69718/internal/service/cloudformation/schemas/AWS_QuickSight_DataSet.json#L899

**Comment by ioannis-klonatos** [comment]
@breathingdust Thanks for taking a look! I just retried and sadly even with this format import does not work.

I assume that DatasetId is the id one gets back from `aws quicksight list-data-sets --aws-account-id <account_id>` and that he can use this account id as the AwsAccountId in the import command, right?

If so, then I am still getting the error:
```
Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: 2ee84a5d-27f1-47a7-9b1b-3a8bfcb74851, api error ValidationException: Identifier
│ <account_id>,<dataset_id> is not valid for identifier [/properties/AwsAccountId, /properties/DataSetId]
```

**Comment by ioannis-klonatos** [comment]
Hey folks... just wanted to add to my comment above (even though this may be a separate ticket):

It is apparently not possible to even create a new data set. Independent of what I try, I get:

> │ Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED.
> StatusMessage: 1 validation error detected: Value null at 'physicalTableMap' failed to satisfy constraint: Member must not be 
>null (Service:
> │ QuickSight, Status Code: 400, Request ID: 341b2c1d-eb61-4b94-89e8-10490a87774f, Extended Request ID: null). ErrorCode: GeneralServiceException

It seems the given physical_table_map is completely ignored? Not sure.
