### ISSUE TITLE
awscc_lakeformation_principal_permissions resource.data_cells_filter GetResource error

### ISSUE THREAD

**Issue by vwightman** [hashicorp/terraform-provider-awscc#719]
`awscc_lakeformation_principal_permissions` for `resource.data_cells_filter` **correctly creates the permission** for a data cell filter & saves the definition to terraform state, **BUT then throws an error when calling the Cloud Control API service GetResource operation**

The GetResource error occurs after the permission is first created with `terraform apply`.  Then the error returns on subsequent `terraform plan`, effectively halting any terraform processing.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

```
Terraform v1.2.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
+ provider registry.terraform.io/hashicorp/awscc v0.36.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
```

### Affected Resource(s)

* awscc_lakeformation_principal_permissions resource.data_cells_filter

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
bucket                = "bucket"
key                   = "terraform/app_lakeform/terraform.tfstate"
region                = "us-east-2"
dynamodb_table        = "tfstate_app_lakeform"
workspace_key_prefix  = ""
acl                   = "bucket-owner-full-control"
profile               = "stg"
```

### Debug Output

Here is the Gist link to the terraform code and apply & plan output:
[GitHub Gist Link](https://gist.github.com/vwightman/28c771020ce5b035b7347678bee1c293#file-awscc_lakeformation_principal_permissions_error-txt)

To summarize: 
Terraform error after successful apply (repeated 10 times)
```
│ Error: Provider returned invalid result object after apply
│
│ After the apply operation, the provider still indicated an unknown value for awscc_lakeformation_principal_permissions.role_dc_test.catalog. All values must be known after apply, so this is always a bug in the provider and    
│ should be reported in the provider's own repository. Terraform will still save the other known object values in the state.
```
Followed by the error:
```
│ Error: AWS SDK Go Service Operation Unsuccessful
│
│   on dl_data_cells_filter.tf line 72, in resource "awscc_lakeformation_principal_permissions" "role_dc_test":
│   72: resource "awscc_lakeformation_principal_permissions" "role_dc_test" {
│
│ Calling Cloud Control API service GetResource operation returned: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: 373c27e6-4002-404c-a099-b16088a427c8, api error
│ ValidationException: When specifying the identifier as JSON, you must specify exactly one identifier from [[/properties/PrincipalIdentifier, /properties/ResourceIdentifier]], and no additional properties can be specified      
```

### Panic Output

N/A

### Expected Behavior

1. The lake formation permission for the data cell filter is successfully created with `terraform apply`
2. The terraform resource is successfully saved in terraform state 
3. The terraform resource can be refreshed, updated or removed with `terraform plan` or `terraform apply`

### Actual Behavior

1. The lake formation permission for the data cell filter is successfully created with `terraform apply`
2. The terraform resource is successfully saved in terraform state (maybe? there is an entry in the state)
3. The terraform resource throws an error when running `terraform plan` or `terraform apply`

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids

Currently the aws provider does not offer permissions management for data_cells_filters.  The aws provider can manage permissions for everything else (data_location, database, lf_tag, lf_tag_policy, table, & table_with_columns), Literally, the only missing resource type is data_cell_filters!

Having the awscc  provider offer the permissions for data_cells_filter is currently the best option to automate the maintenance of this important aws data lake security feature. Any help is much appreciated!

### References

N/A

* #0000

**Comment by breathingdust** [comment]
Related in Standard Provider:
- https://github.com/hashicorp/terraform-provider-aws/issues/27677
- https://github.com/hashicorp/terraform-provider-aws/issues/26687

**Comment by heorhii-bolotov** [comment]
@breathingdust noticed pulumi aws-native has the same issue. 

They proposed a workaround:
{"PrincipalIdentifier":"{"DataLakePrincipalIdentifier": "<roleArn>"}","ResourceIdentifier":"<permissionsJsonStr>"}
instead of
'{"DataLakePrincipalIdentifier":"<roleArn>"} | {<permissionsJson>}'

https://github.com/pulumi/pulumi-aws-native/issues/648
