### ISSUE TITLE
Concurrent operations not working : Multiple Fargate Profiles with Amazon EKS

### ISSUE THREAD

**Issue by maheshr-amzn** [hashicorp/terraform-provider-awscc#796]
### Terraform CLI and Terraform AWS Cloud Control Provider Version

```
terraform -v
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.43.0
+ provider registry.terraform.io/hashicorp/awscc v0.43.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

### Affected Resource(s)

* awscc_eks_fargate_profile
* awscc_eks_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.
I have the below awscc terraform resources of fargate profile and corresponding other AWS resources for fargate profile: IAM, security group, local variables, outputs created as a terraform module in a directory modules/eks_fargate_profile
```hcl
resource "awscc_eks_fargate_profile" "aws_ia_fargateprofile" {
  count = var.use_awscc ? 1 : 0
  fargate_profile_name   = local.fargate_profile["fp_name"] != null ? local.fargate_profile["fp_name"] : null
  cluster_name           = var.eks_cluster_name
  subnets                = local.fargate_profile["subnet_ids"]
  pod_execution_role_arn = var.create_fp_iam_resources ? awscc_iam_role.aws_ia_fargate_profile_role[0].arn : var.iam_role_arn
  selectors = [
    {
      namespace = local.fp_namespace
      labels = local.fargate_profile["labels"]
    }
  ]
  tags       = var.tags
  depends_on = [kubernetes_namespace.aws_ia_fp_namespace]
}
```
Then I am calling this module in this way:
main.tf:
```hcl
module "awscc_ia_eks_fargateprofile" {
  for_each = { for key, value in var.fargate_profiles : key => value
    if length(var.fargate_profiles) > 0
  }
  source = "./modules/eks_fargate_profile"
  eks_cluster_name             = module.aws-ia_eks_label.id
  use_awscc                    = true
  fargate_profiles             = each.value
  depends_on                   = [module.awscc_ia_eks_cluster.eks_cluster_id]
}
```
I am passing a autotf vars file, whose contents are below, value of variable fargate_profiles is declared here (map of any):
```hcl
fargate_profiles = {
  fp1 = {
    fp_name            = "ext-bos-dev1-ops-fp"
    create_namespace   = true
    new_namespace_name = "bosops"
    existing_namespace = null
    subnet_ids = ["subnet-xxxx", "subnet-xxxx"]
    labels = [
       {
         key = "entity"
         value = "finance"
       }
     ]
  },
  fp2 = {
    fp_name            = "ext-bos-dev2-ops-fp"
    create_namespace   = true
    new_namespace_name = "bosdev"
    existing_namespace = null
    subnet_ids = ["subnet-xxxx", "subnet-xxxx"]
     labels = [
       {
         key = "entity"
         value = "financebkp"
       }
     ]
  },
  fp3 = {
    fp_name            = "ext-bos1-coredns-fp"
    create_namespace   = false
    new_namespace_name = ""
    existing_namespace = "kube-system"
    subnet_ids = ["subnet-xxxx", "subnet-xxxx"]
    labels = [
       {
         key = "eks.amazonaws.com/component"
         value = "coredns"
       },
       {
         key = "k8s-app"
         value = "kube-dns"
       }
     ]
  }
}
```

As you can see from above, my aim here is to create 3 fargate profiles, 2 fargate profiles with new namespaces and one for kube-system namespace which already exists in Amazon EKS cluster. I have tested the equivalent TF code for multiple fargate profiles creation concurrently using terraform aws provider, it works using aws provider. But when I use awscc provider, I get the error as mentioned below
### Debug Output
![image](https://user-images.githubusercontent.com/80021638/208593247-6aea9149-fb75-4a9f-ab67-8841c99e9a74.png)

### Panic Output
![image](https://user-images.githubusercontent.com/80021638/208593678-f2ce2349-cd0e-4812-83b1-f2e89921258a.png)

### Expected Behavior

terraform apply should have run multiple fargate profiles creation concurrently, the way it works using terraform aws provider.

### Actual Behavior

terraform apply fails with the error that cannot create fargate profile, since the previous one is in creating state. The same happens with terraform destroy, it can't destroy a specific fargate profile , since the previous one is in deleting state.

### Steps to Reproduce

1. `terraform apply`

### Additional Context
Another related issue is, after the above terraform apply runs and it fails with those errors, I make some changes to tfvars file, for example removing 2 of the fargate profile data from fargate_profiles variable as mentioned below and try to run with only one fargate profile.
```hcl
fargate_profiles = {
  fp3 = {
    fp_name            = "ext-bos1-coredns-fp"
    create_namespace   = false
    new_namespace_name = ""
    existing_namespace = "kube-system"
    subnet_ids = ["subnet-xxxx", "subnet-xxxx"]
    labels = [
       {
         key = "eks.amazonaws.com/component"
         value = "coredns"
       },
       {
         key = "k8s-app"
         value = "kube-dns"
       }
     ]
  }
}
```

Now if I run terraform apply, both fargate profiles are scheduled for removal and in addition to that it says other resources like Amazon EKS cluster and corresponding security groups will be re-created. I am not sure why this behaviour happens. I dont notice this behaviour using terraform aws provider.

**Comment by breathingdust** [comment]
Hi @maheshr-amzn! 👋 I have confirmed with AWS support that Fargate Profiles cannot be created concurrently and that is a service restriction that applies to the both the Cloud Control API and AWS Go SDK (on which the standard provider is built). On looking into the `aws_eks_fargate_profile` resources, I can see that there is special handling that will force creation of the profiles to happen serially:

https://github.com/hashicorp/terraform-provider-aws/blob/12591b060359c993503fc64f28ac993c5dc3896c/internal/service/eks/fargate_profile.go#L126-L129

At this time, this kind of resource specific special handling is not feasible within the Cloud Control provider is it is entirely generated. Unless there is a signal from the schema that this behavior is to be expected, we cannot add handling to do so.

That said I will raise this with the Cloud Control team as an area of potential improvement.
