### ISSUE TITLE
awscc_oam_sink resource fails on apply for valid iam policy document

### ISSUE THREAD

**Issue by soumya-barman-sea** [hashicorp/terraform-provider-awscc#836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Terraform CLI and Terraform AWS Cloud Control Provider Version

Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.53.0
+ provider registry.terraform.io/hashicorp/awscc v0.45.0

### Affected Resource(s)

awscc_oam_sink

### Terraform Configuration Files

```hcl
resource "awscc_oam_sink" "example" {
  name   = "example"
  policy = jsonencode(jsondecode(data.aws_iam_policy_document.example_policy.json))
}

data "aws_iam_policy_document" "example_policy" {
  version = "2012-10-17"
  statement {
    sid    = "AllowMetricDataPush"
    effect = "Allow"
    actions = [
      "oam:CreateLink",
      "oam:UpdateLink"
    ]
    resources = ["*"]
    principals {
      identifiers = [
        "*"
      ]
      type = "*"
    }
    condition {
      test     = "ForAnyValue:StringLike"
      variable = "aws:PrincipalOrgPaths"
      values   = ["0xx/dasd"]
    }
    condition {
      test     = "ForAllValues:StringEquals"
      variable = "oam:ResourceTypes"
      values   = ["AWS::CloudWatch::Metric"]
    }
  }
}
```

### Expected Behavior

The sink gets created in the current account so that it can be used as a monitoring account in CloudWatch cross-account observability.

### Actual Behavior

 Error: Incorrect attribute value type
│ 
│   on modules/bootstrapping/cw_observability.tf line 3, in resource "awscc_oam_sink" "example":
│    3:   policy = jsonencode(jsondecode(data.aws_iam_policy_document.example_policy.json))
│ 
│ Inappropriate value for attribute "policy": map of string required.

### Steps to Reproduce

1. `terraform apply`

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-oam-sink.html
* https://docs.aws.amazon.com/OAM/latest/APIReference/API_CreateSink.html
* https://github.com/hashicorp/terraform-provider-awscc/issues/514

**Comment by ewbankkit** [comment]
@soumya-barman-sea Thanks for raising this issue 👏.
Could you please try using just the Terraform [`jsondecode`](https://developer.hashicorp.com/terraform/language/functions/jsondecode) function?

```
policy = jsondecode(data.aws_iam_policy_document.example_policy.json)
```

**Comment by soumya-barman-sea** [comment]
@ewbankkit It didn't work. See the error below
```
╷
│ Error: Incorrect attribute value type
│ 
│   on modules/bootstrapping/cw_observability.tf line 3, in resource "awscc_oam_sink" "example":
│    3:   policy = jsondecode(data.aws_iam_policy_document.example_policy.json)
│     ├────────────────
│     │ data.aws_iam_policy_document.example_policy.json is "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"AllowMetricDataPush\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"oam:UpdateLink\",\n        \"oam:CreateLink\"\n      ],\n      \"Resource\": \"*\",\n      \"Principal\": \"*\",\n      \"Condition\": {\n        \"ForAllValues:StringEquals\": {\n          \"oam:ResourceTypes\": \"AWS::CloudWatch::Metric\"\n        },\n        \"ForAnyValue:StringLike\": {\n          \"aws:PrincipalOrgPaths\": \"0xx/dasd\"\n        }\n      }\n    }\n  ]\n}"
│ 
│ Inappropriate value for attribute "policy": element "Statement": string required.

```

**Comment by parmouraly** [comment]
Hitting the same issue.
I think at the heart of this issue, I can't understand why the type of `policy` is a a map of string. Should it not simply be a string, ie the policy?
Even looking at the cloud formation docs, the expected type is `json`
```
{
  "Type" : "AWS::Oam::Sink",
  "Properties" : {
      "Name" : String,
      "Policy" : Json,
      "Tags" : {Key : Value, ...}
    }
}
```

It escapes me how is that then translated to `map(string)` in the provider.

**Comment by kadrach** [comment]
`AWS::Oam::Sink.Policy` is a schema-less resource.

https://github.com/hashicorp/terraform-provider-awscc/blob/0eb0e4debd769c3b0fdda7ea0c4504bc87debb53/internal/service/cloudformation/schemas/AWS_Oam_Sink.json#L17-L20

This is translated to `map(string)` (see below), but there is an exception case for `AWS::NetworkManager::CoreNetwork.PolicyDocument` that could be re-used here. I'm unsure how the team is looking to manage this going forward (resource-by-resource fixes seem undesirable).

https://github.com/hashicorp/terraform-provider-awscc/blob/0eb0e4debd769c3b0fdda7ea0c4504bc87debb53/internal/provider/generators/shared/codegen/emitter.go#L628-L652

---
```diff
diff --git a/internal/provider/generators/shared/codegen/emitter.go b/internal/provider/generators/shared/codegen/emitter.go
index 619a1d9f..c52fc134 100644
--- a/internal/provider/generators/shared/codegen/emitter.go
+++ b/internal/provider/generators/shared/codegen/emitter.go
@@ -626,7 +626,8 @@ func (e Emitter) emitAttribute(attributeNameMap map[string]string, path []string
 		// Object.
 		//
 		if len(property.Properties) == 0 {
-			if *e.CfResource.TypeName == "AWS::NetworkManager::CoreNetwork" && len(path) == 1 && name == "PolicyDocument" {
+			if ((*e.CfResource.TypeName == "AWS::NetworkManager::CoreNetwork") && len(path) == 1 && name ==
+			"PolicyDocument") || ((*e.CfResource.TypeName == "AWS::Oam::Sink") && len(path) == 1 && name == "Policy"){
 				// Hack for AWS::NetworkManager::CoreNetwork.PolicyDocument.
 				e.printf("schema.StringAttribute{/*START ATTRIBUTE*/\n")
 				e.printf("CustomType:generic.JSONStringType,\n")
```

```hcl
resource "awscc_oam_sink" "example" {
  name   = "example"
  policy = data.aws_iam_policy_document.example_policy.json
}
```
