### ISSUE TITLE
Add support for AWS::Chatbot::MicrosoftTeamsChannelConfiguration

### ISSUE THREAD

**Issue by absa-rsuarez** [hashicorp/terraform-provider-awscc#879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

Add support for the new AWS::Chatbot::MicrosoftTeamsChannelConfiguration resource which aligns with the existing Slack support

### New or Affected Resource(s)

AWS::Chatbot::MicrosoftTeamsChannelConfiguration

* awscc_chatbot_teams_channel_configuration

### Potential Terraform Configuration

```hcl
resource "awscc_chatbot_teams_channel_configuration" {
configuration_name = "config-name"
iam_role_arn = var.chatbot_role_arn
team_id = var.team_id
teams_channel_id = var.teams_channel_id
teams_tenant_id = var.teams_tenant_id
}
```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-chatbot-microsoftteamschannelconfiguration.html

https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/chatbot_slack_channel_configuration

* #0000

**Comment by breathingdust** [comment]
Hi @absa-rsuarez, as long as AWS adds support via a Cloud Control compatible CloudFormation handler (which it has) then support for this will come out in the next version of the provider. We do not typically track coverage requests in this repo as coverage is dictated upstream at AWS.
